"use strict";
const canvas=document.getElementById("game-canvas"),ctx=canvas.getContext("2d"),$=id=>document.getElementById(id);
const ui={battleHud:$("battle-hud"),commandBar:$("command-bar"),mainMenu:$("main-menu"),pauseMenu:$("pause-menu"),resultMenu:$("result-menu"),status:$("status"),selectionTitle:$("selection-title"),deploy:$("deploy-button"),shield:$("shield-button"),blueTowers:$("blue-towers"),redTowers:$("red-towers"),matchTime:$("match-time"),matchStatus:$("match-status"),pause:$("pause-button"),start:$("start-button"),level2:$("level-2-button"),resume:$("resume-button"),restart:$("restart-button"),resultTitle:$("result-title"),resultKicker:$("result-kicker"),resultDetail:$("result-detail"),debugPanel:$("debug-panel"),special:$("special-button"),debugUnits:$("debug-units"),debugProjectiles:$("debug-projectiles"),debugDamage:$("debug-damage")};
const C={towerHp:150,towerDamage:12,towerRate:1,soldierHp:150,soldierDamage:10,soldierRate:.85,soldierSpeed:3.4,soldierRange:12,smashRange:2.8,smashDamage:55,smashRate:1.15,shieldUses:3,shieldDuration:5,shieldCooldown:10,shotSpeed:48,barrierHp:240,specialApproach:2.4,specialStrike:0.5,worldWidth:50,worldDepth:72};
const levels={easy:{delay:1.9,aim:.45,shield:.42,fireRate:1.8,deploy:[Infinity,Infinity]},medium:{delay:1.1,aim:.72,shield:.68,fireRate:1.4,deploy:[7,11]},hard:{delay:.55,aim:.95,shield:.9,fireRate:1,deploy:[3.5,6]}};
let audio=null,lastImpact=0,viewport={w:1,h:1,dpr:1};
const game={phase:"menu",difficulty:"medium",playerTeam:"blue",aiTeam:"red",world:1,worldBattle:1,level:1,startingTowers:3,lastResult:null,elapsed:0,lastTime:performance.now(),selectedId:null,manualTargetId:null,orderFriendlyId:null,orderEnemyId:null,lastOrderFriendlyId:null,lastOrderTargetId:null,deployArmedUntil:0,entities:[],barriers:[],projectiles:[],particles:[],rings:[],specialUnits:[],damageDealt:0,nextSoldier:1,nextShot:1,cameraShake:0,aiAt:0,aiDeployAt:Infinity,shields:{},specials:{}};
const art={background:new Image(),riftBackground:new Image(),blueTower:new Image(),redTower:new Image(),blueGiant:new Image(),redMegalodon:new Image(),blueBarrier:new Image(),redBarrier:new Image(),destroyedBarrier:new Image()};art.background.src="assets/alien-battlefield.png";art.riftBackground.src="assets/world2-rift-background.png";art.blueTower.src="assets/blue-tower.png";art.redTower.src="assets/red-tower.png";art.blueGiant.src="assets/blue-giant.png";art.redMegalodon.src="assets/red-megalodon.png";art.blueBarrier.src="assets/world2-shield-blue.png";art.redBarrier.src="assets/world2-shield-red.png";art.destroyedBarrier.src="assets/world2-shield-destroyed.png";
function tower(id,team,x,z){return{id,team,kind:"tower",x,z,hp:C.towerHp,maxHp:C.towerHp,alive:true,deployed:false,rearmStartedAt:0,weaponReadyAt:0,targetId:null,nextFire:Math.random()*.45+.35,nextSmash:0,orderedUntil:0,hitFlash:0,shieldUntil:0}}
function formation(count,near){const rowCount=Math.max(2,Math.ceil(count/5)),zMin=7,zMax=32,base=Math.floor(count/rowCount),extra=count%rowCount,counts=Array.from({length:rowCount},(_,row)=>base+(row<extra?1:0)),result=[];for(let row=0;row<rowCount;row++){const columns=counts[row],spacing=columns===1?0:Math.min(12,32/(columns-1));let start=row,end=row;while(start>0&&counts[start-1]===columns)start--;while(end<rowCount-1&&counts[end+1]===columns)end++;const groupLength=end-start+1,offsets=groupLength===2?[-3,3]:groupLength===3?[-3,3,0]:[-3,3,-1.5,1.5,0],shift=groupLength>1?offsets[(row-start)%offsets.length]:0,z=zMin+(zMax-zMin)*row/(rowCount-1);for(let column=0;column<columns;column++){const x=(column-(columns-1)/2)*spacing+shift;result.push({x,z:near?z:-z})}}return result}
const RIFT_SLOTS={nearPlateau:[[.13,.51],[.24,.52],[.18,.60],[.30,.59],[.08,.60],[.31,.50]],nearLow:[[.51,.77],[.64,.77],[.57,.84],[.70,.84],[.48,.87],[.73,.76]],farPlateau:[[.53,.20],[.64,.20],[.58,.14],[.47,.14],[.69,.13],[.73,.20]],farLow:[[.80,.38],[.91,.37],[.85,.31],[.95,.30],[.75,.31],[.96,.39]]};
const RIFT_BARRIER_SPECS={nearPlateau:{nx:.31,ny:.35,width:.25,angle:.20},nearLow:{nx:.61,ny:.64,width:.28,angle:.18},farPlateau:{nx:.53,ny:.29,width:.23,angle:.13},farLow:{nx:.80,ny:.50,width:.27,angle:.16}};
function mapPosition(nx,ny){return{x:(nx-.5)*C.worldWidth,z:(ny-.5)*C.worldDepth}}
function riftTowersPerBarrier(){return Math.min(6,game.worldBattle+1)}
function barrier(id,team,group,spec){const p=mapPosition(spec.nx,spec.ny);return{id,team,kind:"barrier",group,x:p.x,z:p.z,hp:C.barrierHp,maxHp:C.barrierHp,alive:true,hitFlash:0,mapWidth:spec.width,angle:spec.angle}}
function addRiftSide(team,prefix,groups,count){let number=1;for(const group of groups){const barrierId=prefix+"-"+(group.includes("Plateau")?"P":"L");game.barriers.push(barrier(barrierId,team,group,RIFT_BARRIER_SPECS[group]));for(const slot of RIFT_SLOTS[group].slice(0,count)){const p=mapPosition(slot[0],slot[1]),t=tower(prefix+(number++),team,p.x,p.z);t.barrierId=barrierId;t.riftGroup=group;game.entities.push(t)}}}
function setupOpenField(){game.startingTowers=game.level+2;const near=game.playerTeam,far=game.aiTeam,np=near==="blue"?"B":"R",fp=far==="blue"?"B":"R",nearSlots=formation(game.startingTowers,true),farSlots=formation(game.startingTowers,false);nearSlots.forEach((p,i)=>game.entities.push(tower(np+(i+1),near,p.x,p.z)));farSlots.forEach((p,i)=>game.entities.push(tower(fp+(i+1),far,p.x,p.z)))}
function setupRift(){const count=riftTowersPerBarrier(),near=game.playerTeam,far=game.aiTeam,np=near==="blue"?"B":"R",fp=far==="blue"?"B":"R";game.startingTowers=count*2;addRiftSide(near,np,["nearPlateau","nearLow"],count);addRiftSide(far,fp,["farPlateau","farLow"],count)}
function aiDeployDelay(){const [min,max]=levels[game.difficulty].deploy;return Number.isFinite(min)?min+(max-min)*Math.random():Infinity}
function resetMatch(){game.aiTeam=game.playerTeam==="blue"?"red":"blue";Object.assign(game,{elapsed:0,selectedId:null,manualTargetId:null,orderFriendlyId:null,orderEnemyId:null,lastOrderFriendlyId:null,lastOrderTargetId:null,deployArmedUntil:0,barriers:[],projectiles:[],particles:[],rings:[],specialUnits:[],damageDealt:0,nextSoldier:1,nextShot:1,cameraShake:0,aiAt:.8,aiDeployAt:aiDeployDelay(),shields:{blue:{uses:3,activeUntil:0,readyAt:0},red:{uses:3,activeUntil:0,readyAt:0}},specials:{blue:{used:false},red:{used:false}}});game.entities=[];if(game.world===2)setupRift();else setupOpenField();setStatus("No unit selected",game.world===2?"Break an enemy barrier to expose the towers behind it.":"Select one of your units and an enemy target, in either order.");updateHud()}
function startMatch(){resetMatch();game.phase="playing";game.lastTime=performance.now();ui.mainMenu.classList.add("hidden");ui.pauseMenu.classList.add("hidden");ui.resultMenu.classList.add("hidden");ui.battleHud.classList.remove("hidden");ui.commandBar.classList.remove("hidden");ensureAudio();sound("start")}
function startLevel2(){game.world=2;game.worldBattle=1;game.lastResult=null;startMatch()}
function showMainMenu(){game.phase="menu";game.world=1;game.worldBattle=1;game.level=1;game.lastResult=null;resetMatch();ui.mainMenu.classList.remove("hidden");ui.pauseMenu.classList.add("hidden");ui.resultMenu.classList.add("hidden");ui.battleHud.classList.add("hidden");ui.commandBar.classList.add("hidden")}
function pauseGame(){if(game.phase!=="playing")return;game.phase="paused";ui.pauseMenu.classList.remove("hidden")}
function resumeGame(){if(game.phase!=="paused")return;game.phase="playing";game.lastTime=performance.now();ui.pauseMenu.classList.add("hidden")}
function endMatch(result){if(game.phase!=="playing")return;game.phase="result";game.lastResult=result;ui.resultMenu.classList.remove("hidden");ui.resultKicker.textContent=result==="victory"?game.world===1&&game.level===18?"WORLD 1 CLEARED":"ENEMY NETWORK DESTROYED":result==="defeat"?game.playerTeam.toUpperCase()+" NETWORK LOST":"STALEMATE";ui.resultTitle.textContent=result==="victory"?game.world===1&&game.level===18?"The Rift Awaits":"Victory":result==="defeat"?"Defeat":"Draw";if(result==="victory")ui.resultDetail.textContent=game.world===1?(game.level===18?"The next battle begins World 2 with two towers behind each energy barrier.":"Battle "+game.level+" cleared. The next battle has "+(game.startingTowers+1)+" towers per team."):(riftTowersPerBarrier()<6?"Rift battle "+game.worldBattle+" cleared. One tower will be added behind every barrier.":"Rift battle "+game.worldBattle+" cleared. Each barrier now guards the maximum six towers.");else if(result==="defeat")ui.resultDetail.textContent=game.world===1?"Replay battle "+game.level+" with "+game.startingTowers+" towers per team.":"Replay Rift battle "+game.worldBattle+" with "+riftTowersPerBarrier()+" towers behind each barrier.";else ui.resultDetail.textContent="Neither force can damage the remaining structures.";ui.restart.textContent=result==="victory"?game.world===1&&game.level===18?"Enter World 2":"Next Battle":"Replay Battle";sound(result==="victory"?"victory":"defeat")}
function continueBattle(){if(game.lastResult==="victory"){if(game.world===1&&game.level>=18){game.world=2;game.worldBattle=1}else if(game.world===1)game.level++;else game.worldBattle++}startMatch()}
function ensureAudio(){if(audio){if(audio.state==="suspended")audio.resume();return}const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A}
function sound(type){if(!audio)return;const now=audio.currentTime;if(type==="impact"&&now-lastImpact<.08)return;if(type==="impact")lastImpact=now;const map={start:[220,440,.18,.05],shoot:[390,190,.07,.012],impact:[150,80,.09,.025],shield:[180,520,.35,.045],explode:[95,38,.28,.07],victory:[330,660,.65,.055],defeat:[180,65,.55,.05]},v=map[type]||map.impact,o=audio.createOscillator(),g=audio.createGain();o.type=type==="impact"||type==="explode"?"sawtooth":"sine";o.frequency.setValueAtTime(v[0],now);o.frequency.exponentialRampToValueAtTime(v[1],now+v[2]);g.gain.setValueAtTime(v[3],now);g.gain.exponentialRampToValueAtTime(.0001,now+v[2]);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+v[2])}
function byId(id){return game.entities.find(e=>e.id===id)||game.barriers.find(e=>e.id===id)}
function activeBarrierFor(target){return target&&target.kind==="tower"&&target.barrierId?game.barriers.find(b=>b.id===target.barrierId&&b.alive):null}
function structureTargets(team){const barriers=game.barriers.filter(b=>b.alive&&b.team===team),towers=living(team,"tower").filter(t=>!activeBarrierFor(t));return barriers.concat(towers)}
function attackableTarget(target){return activeBarrierFor(target)||target}
function living(team,kind){return game.entities.filter(e=>e.alive&&(!team||e.team===team)&&(!kind||e.kind===kind))}
function weaponOffline(e){return e.kind==="tower"&&e.deployed&&game.elapsed<e.weaponReadyAt}
function canAttack(e){return e.alive&&(e.kind==="soldier"||!weaponOffline(e))}
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function autoTarget(a){const enemyTeam=a.team==="blue"?"red":"blue",enemies=living(enemyTeam),soldiers=enemies.filter(e=>e.kind==="soldier"),structures=structureTargets(enemyTeam);let pool=soldiers.length?soldiers:structures;if(!pool.length)return null;if(a.kind==="soldier"&&!soldiers.length){pool.sort((x,y)=>dist(a,x)-dist(a,y));return pool[0]}if(a.team===game.aiTeam&&Math.random()>levels[game.difficulty].aim)return pool[Math.floor(Math.random()*pool.length)];pool.sort((x,y)=>{const damaged=x.hp/x.maxHp-y.hp/y.maxHp;return Math.abs(damaged)>.18?damaged:dist(a,x)-dist(a,y)});return pool[0]}
function assignTarget(target,attacker){if(!target||!attacker||attacker.team!==game.playerTeam||!canAttack(attacker))return false;attacker.targetId=target.id;attacker.orderedUntil=Number.MAX_VALUE;game.manualTargetId=target.id;game.lastOrderFriendlyId=attacker.id;game.lastOrderTargetId=target.id;game.orderFriendlyId=null;game.orderEnemyId=null;setStatus(attacker.id+" focusing "+target.id,attacker.kind==="soldier"?"Soldier will fire while advancing and smash the target at close range.":"This tower will keep firing at the selected target.");addRing(attacker.x,attacker.z,"gold",.5);addRing(target.x,target.z,"red",.7);return true}
function spawnSoldier(t,announce=t.team===game.playerTeam){t.deployed=true;t.weaponReadyAt=Infinity;t.targetId=null;const s={id:(t.team==="blue"?"B-S":"R-S")+game.nextSoldier++,team:t.team,kind:"soldier",sourceTowerId:t.id,x:t.x,z:t.z-2.5,hp:C.soldierHp,maxHp:C.soldierHp,alive:true,targetId:null,nextFire:game.elapsed,nextSmash:game.elapsed,orderedUntil:0,hitFlash:0,shieldUntil:0};game.entities.push(s);if(announce){game.selectedId=s.id;game.deployArmedUntil=0;setStatus(s.id+" deployed",t.id+"'s weapon is offline while its soldier is active.")}burst(t.x,t.z-1,t.team,16);addRing(t.x,t.z,t.team,.9);sound("start");updateHud()}
function handleDeploy(){const t=byId(game.selectedId);if(!t||t.team!==game.playerTeam||t.kind!=="tower"||!t.alive||t.deployed)return;spawnSoldier(t)}
function activateShield(team,targetId){const s=game.shields[team],target=byId(targetId);if(!target||!target.alive||target.team!==team||target.kind==="barrier"){if(team===game.playerTeam)setStatus("Select a unit first","Select one of your towers or walking soldiers, then activate its shield.");return false}if(s.uses<=0||game.elapsed<s.activeUntil||game.elapsed<s.readyAt)return false;s.uses--;s.activeUntil=game.elapsed+C.shieldDuration;s.readyAt=s.activeUntil+C.shieldCooldown;target.shieldUntil=s.activeUntil;addRing(target.x,target.z,team,1.2);if(team===game.playerTeam)setStatus(target.id+" shielded","This unit blocks all incoming damage for five seconds.");sound("shield");updateHud();return true}
function shielded(target){return game.elapsed<(target.shieldUntil||0)}
function fire(a,t){const rate=(a.kind==="tower"?C.towerRate:C.soldierRate)*levels[game.difficulty].fireRate,damage=a.kind==="tower"?C.towerDamage:C.soldierDamage;a.nextFire=game.elapsed+rate;game.projectiles.push({id:game.nextShot++,sourceId:a.id,targetId:t.id,team:a.team,startX:a.x,startZ:a.z,startAt:game.elapsed,duration:Math.max(.22,dist(a,t)/C.shotSpeed),damage});burst(a.x,a.z,a.team,3);if(Math.random()<.35)sound("shoot")}
function hit(target,damage,team){if(!target.alive)return;const blocker=activeBarrierFor(target);if(blocker)return hit(blocker,damage,team);if(shielded(target)){addRing(target.x,target.z,target.team,.34);burst(target.x,target.z,target.team,5);return}target.hp=Math.max(0,target.hp-damage);target.hitFlash=.12;if(team===game.playerTeam)game.damageDealt+=damage;burst(target.x,target.z,target.team==="blue"?"red":"blue",7);sound("impact");if(target.hp<=0)destroy(target)}
function destroy(e){e.alive=false;e.targetId=null;game.cameraShake=e.kind==="barrier"?.7:e.kind==="tower"?.45:.18;burst(e.x,e.z,"fire",e.kind==="barrier"?48:e.kind==="tower"?36:14);addRing(e.x,e.z,"fire",.9);if(e.kind==="tower"||e.kind==="barrier")sound("explode");if(e.kind==="barrier"&&e.team!==game.playerTeam)setStatus(e.id+" breached","The towers behind this barrier are exposed.");if(e.kind==="soldier"&&e.sourceTowerId){const source=byId(e.sourceTowerId);if(source&&source.alive){source.rearmStartedAt=game.elapsed;source.weaponReadyAt=source.rearmStartedAt+3;source.nextFire=source.weaponReadyAt;setStatus(e.id+" destroyed",source.id+" will resume firing in 3 seconds.")}}if(game.selectedId===e.id){game.selectedId=null;if(e.kind!=="soldier"||!e.sourceTowerId)setStatus("Unit destroyed","Select another tower or tap an enemy to redirect fire.")}for(const u of game.entities)if(u.targetId===e.id)u.targetId=null;updateHud()}
function updateCombat(dt){for(const u of game.entities){if(u.hitFlash>0)u.hitFlash-=dt;if(!canAttack(u))continue;let t=byId(u.targetId);if(!t||!t.alive||t.team===u.team){t=autoTarget(u);u.targetId=t?t.id:null;u.orderedUntil=0}if(!t)continue;if(u.kind==="soldier"){const range=dist(u,t),canSmash=(t.kind==="tower"||t.kind==="barrier")&&range<=C.smashRange;if(canSmash){if(game.elapsed>=u.nextSmash){u.nextSmash=game.elapsed+C.smashRate;game.cameraShake=.38;addShockwave(t.x,t.z,u.team);burst(t.x,t.z,"fire",22);hit(t,C.smashDamage,u.team);sound("explode")}}else{if(range>C.smashRange){const dx=t.x-u.x,dz=t.z-u.z,len=Math.max(.001,Math.hypot(dx,dz));u.x+=dx/len*C.soldierSpeed*dt;u.z+=dz/len*C.soldierSpeed*dt}if(game.elapsed>=u.nextFire)fire(u,t)}}else if(game.elapsed>=u.nextFire)fire(u,t)}for(let i=game.projectiles.length-1;i>=0;i--){const s=game.projectiles[i];if(game.elapsed-s.startAt>=s.duration){const t=byId(s.targetId);if(t&&t.alive)hit(t,s.damage,s.team);game.projectiles.splice(i,1)}}}
function specialName(team){return team==="blue"?"Giant":"Megalodon"}
function specialUnlocked(team){return living(team,"tower").length<game.startingTowers}
function deploySpecial(team,targetId=null){const state=game.specials[team],target=targetId?byId(targetId):null;if(!state||state.used||!specialUnlocked(team))return false;if(targetId&&(!target||!target.alive||target.team===team||(target.kind!=="tower"&&target.kind!=="barrier")))return false;state.used=true;const start=game.world===2?mapPosition(team===game.playerTeam?.10:.90,team===game.playerTeam?.90:.12):{x:team==="blue"?-12:14,z:team===game.playerTeam?34:-34},startZ=start.z,startX=start.x;game.specialUnits.push({team,targetId:target?target.id:null,phase:target?"approach":"choosing",x:startX,z:startZ,startX,startZ,progress:0,timer:0});if(team===game.playerTeam)setStatus(specialName(team)+" deployed",target?specialName(team)+" is heading for "+target.id+".":"Tap the enemy barrier or exposed tower "+specialName(team)+" should destroy.");sound("start");updateHud();return true}
function retargetSpecial(unit){const targets=structureTargets(unit.team===game.playerTeam?game.aiTeam:game.playerTeam);if(!targets.length)return null;targets.sort((a,b)=>dist(unit,a)-dist(unit,b));unit.targetId=targets[0].id;unit.phase="approach";unit.progress=0;unit.startX=unit.x;unit.startZ=unit.z;if(unit.team===game.playerTeam)setStatus(specialName(unit.team)+" retargeting","Original target lost. Switching to "+targets[0].id+".");return targets[0]}
function specialEdge(unit,target){const dx=unit.startX-target.x,dz=unit.startZ-target.z,len=Math.max(.001,Math.hypot(dx,dz));return{x:target.x+dx/len*4.4,z:target.z+dz/len*4.4}}
function updateSpecials(dt){for(let i=game.specialUnits.length-1;i>=0;i--){const u=game.specialUnits[i];if(u.phase==="choosing")continue;let target=byId(u.targetId);if((!target||!target.alive)&&u.phase!=="leaving")target=retargetSpecial(u);if(!target&&u.phase!=="leaving"){u.phase="leaving";u.timer=0}if(u.phase==="approach"&&target){const edge=specialEdge(u,target);u.progress=Math.min(1,u.progress+dt/C.specialApproach);const ease=1-Math.pow(1-u.progress,2);u.x=u.startX+(edge.x-u.startX)*ease;u.z=u.startZ+(edge.z-u.startZ)*ease;if(u.progress>=1){u.phase=shielded(target)?"waiting":"striking";u.timer=0}}else if(u.phase==="waiting"&&target){const edge=specialEdge(u,target);u.x=edge.x;u.z=edge.z;if(!shielded(target)){u.phase="striking";u.timer=0;if(u.team===game.playerTeam)setStatus(specialName(u.team)+" attacking",target.id+" shield dropped.");}}else if(u.phase==="striking"&&target){if(shielded(target)){u.phase="waiting";u.timer=0}else{u.timer+=dt;if(u.timer>=C.specialStrike){game.cameraShake=.8;burst(target.x,target.z,"fire",55);addRing(target.x,target.z,"fire",1.2);destroy(target);u.phase="leaving";u.timer=0;if(u.team===game.playerTeam)setStatus(target.id+" destroyed",specialName(u.team)+" completed its attack and is leaving.");sound("explode")}}}else if(u.phase==="leaving"){u.timer+=dt;u.z+=u.team===game.playerTeam?18*dt:-18*dt;u.x+=game.world===2?(u.team===game.playerTeam?-10*dt:10*dt):(u.team==="blue"?-14*dt:14*dt);if(u.timer>=.7)game.specialUnits.splice(i,1)}}}
function updateAI(){if(game.elapsed<game.aiAt)return;const l=levels[game.difficulty],team=game.aiTeam;game.aiAt=game.elapsed+l.delay*(.85+Math.random()*.35);const special=game.specials[team];if(specialUnlocked(team)&&!special.used&&!game.specialUnits.some(u=>u.team===team)){const specialTarget=structureTargets(game.playerTeam).sort((a,b)=>b.hp-a.hp)[0];if(specialTarget)deploySpecial(team,specialTarget.id)}if(game.elapsed>=game.aiDeployAt){const towers=living(team,"tower").filter(t=>!t.deployed);if(towers.length){spawnSoldier(towers[Math.floor(Math.random()*towers.length)],false);game.aiDeployAt=game.elapsed+aiDeployDelay()}else game.aiDeployAt=Infinity}const s=game.shields[team];if(s.uses<=0||game.elapsed<s.readyAt)return;const threatened=game.projectiles.map(p=>byId(p.targetId)).find(t=>t&&t.alive&&t.team===team),endangered=living(team,"tower").find(t=>t.hp<=48),target=endangered||threatened;if(target&&Math.random()<l.shield)activateShield(team,target.id)}
function checkEnd(){if(!living(game.aiTeam,"tower").length)return endMatch("victory");if(!living(game.playerTeam,"tower").length)return endMatch("defeat")}
function addRing(x,z,color,life){game.rings.push({x,z,color,life,maxLife:life})}
function addShockwave(x,z,color){game.rings.push({x,z,color,life:.72,maxLife:.72,shockwave:true})}
function burst(x,z,color,count){for(let i=0;i<count;i++)game.particles.push({x,z,height:3+Math.random()*10,vx:(Math.random()-.5)*8,vz:(Math.random()-.5)*8,vh:5+Math.random()*13,life:.35+Math.random()*.65,maxLife:1,color,size:1.5+Math.random()*3.5})}
function updateRearming(){for(const t of game.entities){if(t.kind!=="tower"||!t.alive||!Number.isFinite(t.weaponReadyAt)||t.weaponReadyAt<=0||game.elapsed<t.weaponReadyAt)continue;t.weaponReadyAt=0;t.nextFire=game.elapsed;addRing(t.x,t.z,t.team,.75);if(t.team===game.playerTeam)setStatus(t.id+" rearmed","Tower weapon is firing again.")}}
function updateEffects(dt){for(const b of game.barriers)if(b.hitFlash>0)b.hitFlash-=dt;for(let i=game.particles.length-1;i>=0;i--){const p=game.particles[i];p.x+=p.vx*dt;p.z+=p.vz*dt;p.height+=p.vh*dt;p.vh-=20*dt;p.life-=dt;if(p.life<=0)game.particles.splice(i,1)}for(let i=game.rings.length-1;i>=0;i--){game.rings[i].life-=dt;if(game.rings[i].life<=0)game.rings.splice(i,1)}game.cameraShake=Math.max(0,game.cameraShake-dt*1.8)}
function update(dt){game.elapsed+=dt;if(game.elapsed>game.deployArmedUntil&&ui.deploy.classList.contains("armed")){game.deployArmedUntil=0;ui.deploy.classList.remove("armed");ui.deploy.textContent="Deploy Soldier"}updateRearming();updateCombat(dt);updateSpecials(dt);updateAI();updateEffects(dt);updateHud();checkEnd()}

function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.5);viewport={w:r.width,h:r.height,dpr:d};canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0)}
function size(){return viewport}
function project(x,z,height=0){const s=size();if(game.world===2){const nx=x/C.worldWidth+.5,ny=z/C.worldDepth+.5,scale=.55+ny;return{x:nx*s.w,y:ny*s.h-height*scale*Math.min(s.w,s.h)/620,scale}}const horizon=s.h*.265,t=(z+C.worldDepth/2)/C.worldDepth,scale=.44+t*1.02,field=Math.min(s.w*.88,s.h*1.55);return{x:s.w/2+x*scale*field/C.worldWidth,y:horizon+t*s.h*.62-height*scale*Math.min(s.w,s.h)/620,scale}}
function drawBackground(now){const s=size(),w=s.w,h=s.h,img=game.world===2?art.riftBackground:art.background;if(img.complete&&img.naturalWidth){if(game.world===2)ctx.drawImage(img,0,0,w,h);else{const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}const shade=ctx.createLinearGradient(0,0,0,h);shade.addColorStop(0,"rgba(13,24,37,.03)");shade.addColorStop(.6,"rgba(20,12,20,0)");shade.addColorStop(1,"rgba(8,8,14,.28)");ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);return}const horizon=h*.265,sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,"#489ed4");sky.addColorStop(.7,"#86c8ec");sky.addColorStop(1,"#d0e9ef");ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon+1);ctx.fillStyle="#7b392f";ctx.fillRect(0,horizon,w,h-horizon);drawGrid();drawCrystals(now)}
function drawMountains(w,h){const layers=[["rgba(66,58,80,.42)",[0,.13,.21,.34,.46,.59,.73,.86,1]],["rgba(72,46,62,.68)",[0,.16,.29,.43,.55,.68,.82,1]]];for(const layer of layers){ctx.fillStyle=layer[0];ctx.beginPath();ctx.moveTo(0,h);layer[1].forEach((p,i)=>ctx.lineTo(p*w,i%2?h-(35+i%3*20):h-h*.06));ctx.lineTo(w,h);ctx.closePath();ctx.fill()}}
function drawGrid(){ctx.save();ctx.strokeStyle="rgba(255,205,137,.12)";ctx.lineWidth=1;for(let z=-32;z<=34;z+=7){const a=project(-23,z),b=project(23,z);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let x=-20;x<=20;x+=5){const a=project(x,-33),b=project(x,35);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}
function drawCrystals(now){const list=[[-19,-4,5,"#9b6fff"],[20,3,7,"#59d5ff"],[-22,24,9,"#8d70ff"],[22,-23,5,"#50c7eb"],[18,29,6,"#b784ff"],[-20,-27,4,"#72d7f4"]];for(const c of list){const b=project(c[0],c[1]),t=project(c[0],c[1],c[2]);ctx.save();ctx.globalAlpha=.72+Math.sin(now*.002+c[0])*.18;ctx.fillStyle=c[3];ctx.beginPath();ctx.moveTo(b.x-3*b.scale,b.y);ctx.lineTo(t.x,t.y);ctx.lineTo(b.x+4*b.scale,b.y);ctx.closePath();ctx.fill();ctx.restore()}}
function color(team){return team==="blue"?"#35c8ff":team==="red"?"#ff554e":team==="gold"?"#ffd56a":"#ffb24d"}
function barrierGeometry(b){const p=project(b.x,b.z),img=b.alive?(b.team==="blue"?art.blueBarrier:art.redBarrier):art.destroyedBarrier,w=b.mapWidth*size().w,ratio=img.naturalWidth&&img.naturalHeight?img.naturalHeight/img.naturalWidth:.52,h=w*ratio;return{p,img,w,h}}
function drawBarriers(){if(game.world!==2)return;for(const b of game.barriers){const g=barrierGeometry(b);ctx.save();ctx.translate(g.p.x,g.p.y);ctx.rotate(b.angle);if(b.hitFlash>0){ctx.shadowColor="#fff";ctx.shadowBlur=24}if(b.id===game.manualTargetId){ctx.strokeStyle="#ffd56a";ctx.lineWidth=3;ctx.strokeRect(-g.w*.48,-g.h*.38,g.w*.96,g.h*.76)}if(g.img.complete&&g.img.naturalWidth)ctx.drawImage(g.img,-g.w/2,-g.h/2,g.w,g.h);ctx.restore();if(b.alive)drawHealth(b,g.p.y-g.h*.42,Math.max(64,g.w*.55))}}
function drawShields(now){for(const u of game.entities){if(!u.alive||game.elapsed>=(u.shieldUntil||0))continue;const p=project(u.x,u.z,u.kind==="tower"?10:5),pulse=.42+Math.sin(now*.008)*.08,w=(u.kind==="tower"?42:24)*p.scale,h=(u.kind==="tower"?58:34)*p.scale;ctx.save();ctx.strokeStyle=u.team==="blue"?"rgba(67,211,255,"+(pulse+.28)+")":"rgba(255,105,95,"+(pulse+.2)+")";ctx.fillStyle=u.team==="blue"?"rgba(45,188,255,"+(pulse*.23)+")":"rgba(255,75,70,"+(pulse*.18)+")";ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,w,h,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}}
function drawHealth(u,y,width){const b=project(u.x,u.z),pct=Math.max(0,u.hp/u.maxHp);ctx.fillStyle="rgba(4,8,10,.72)";ctx.fillRect(b.x-width/2,y,width,5);ctx.fillStyle=pct<.3?"#ffd15d":color(u.team);ctx.fillRect(b.x-width/2+1,y+1,Math.max(0,(width-2)*pct),3)}
function drawTower(u,now){const b=project(u.x,u.z),s=b.scale,c=color(u.team),selected=u.id===game.selectedId,targeted=u.id===game.manualTargetId,img=u.team==="blue"?art.blueTower:art.redTower,height=116*s,width=height*.667,offline=weaponOffline(u);ctx.save();ctx.fillStyle="rgba(0,0,0,.4)";ctx.beginPath();ctx.ellipse(b.x,b.y+5*s,width*.38,9*s,0,0,Math.PI*2);ctx.fill();if(!u.alive){ctx.globalAlpha=.8;ctx.filter="grayscale(1) brightness(.36)";if(img.complete&&img.naturalWidth)ctx.drawImage(img,b.x-width*.4,b.y-height*.28,width*.8,height*.28);ctx.filter="none";ctx.globalAlpha=1;ctx.fillStyle="rgba(18,15,16,.75)";ctx.beginPath();ctx.ellipse(b.x,b.y,width*.34,8*s,0,0,Math.PI*2);ctx.fill();ctx.restore();return}if(selected||targeted||u.orderedUntil>game.elapsed){ctx.strokeStyle=selected?"#ffd56a":targeted?c:"#fff0a0";ctx.lineWidth=3;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=10;ctx.beginPath();ctx.ellipse(b.x,b.y+3*s,width*.46,12*s,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}if(img.complete&&img.naturalWidth){if(offline){ctx.globalAlpha=.58;ctx.filter="saturate(.35) brightness(.7)"}if(u.hitFlash>0){ctx.shadowColor="#fff";ctx.shadowBlur=24}ctx.drawImage(img,b.x-width/2,b.y-height+7*s,width,height);ctx.filter="none";ctx.shadowBlur=0;ctx.globalAlpha=1}else{ctx.fillStyle=u.team==="blue"?"#b8d3dc":"#30353a";ctx.fillRect(b.x-width*.22,b.y-height*.82,width*.44,height*.82);ctx.fillStyle=c;ctx.fillRect(b.x-2*s,b.y-height*.78,4*s,height*.62)}if(offline){ctx.strokeStyle="#ffd56a";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x-width*.25,b.y-height*.3);ctx.lineTo(b.x+width*.25,b.y-height*.3);ctx.stroke()}if(offline&&Number.isFinite(u.weaponReadyAt)){const remaining=Math.max(1,Math.ceil(u.weaponReadyAt-game.elapsed));ctx.font="700 "+Math.max(12,14*s)+"px Segoe UI";ctx.textAlign="center";ctx.fillStyle="#ffd56a";ctx.shadowColor="rgba(0,0,0,.9)";ctx.shadowBlur=5;ctx.fillText(remaining+"s",b.x,b.y-height-18);ctx.shadowBlur=0}drawHealth(u,b.y-height-10,width*.82);ctx.restore()}
function drawSoldier(u,now){if(!u.alive)return;const b=project(u.x,u.z),h=project(u.x,u.z,10),s=b.scale,c=color(u.team);ctx.save();ctx.fillStyle="rgba(0,0,0,.3)";ctx.beginPath();ctx.ellipse(b.x,b.y+3*s,10*s,4*s,0,0,Math.PI*2);ctx.fill();if(u.id===game.selectedId||u.orderedUntil>game.elapsed){ctx.strokeStyle="#ffd56a";ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(b.x,b.y+2*s,15*s,6*s,0,0,Math.PI*2);ctx.stroke()}ctx.strokeStyle=u.hitFlash>0?"#fff":u.team==="blue"?"#b9d7df":"#555c61";ctx.lineWidth=7*s;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(b.x,b.y-3*s);ctx.lineTo(b.x,h.y+4*s);ctx.stroke();ctx.fillStyle=c;ctx.beginPath();ctx.arc(b.x,h.y,5.5*s,0,Math.PI*2);ctx.fill();const d=u.team==="blue"?-1:1;ctx.strokeStyle=c;ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(b.x+d*2*s,h.y+9*s);ctx.lineTo(b.x+d*18*s,h.y+5*s);ctx.stroke();ctx.fillStyle=c;ctx.globalAlpha=.35+Math.sin(now*.009+u.x)*.15;ctx.beginPath();ctx.arc(b.x,h.y+7*s,8*s,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;drawHealth(u,h.y-10,26*s);ctx.restore()}
function shotPosition(s){const t=byId(s.targetId),p=Math.min(1,(game.elapsed-s.startAt)/s.duration),e=1-Math.pow(1-p,2),x=t?t.x:s.startX,z=t?t.z:s.startZ;return{x:s.startX+(x-s.startX)*e,z:s.startZ+(z-s.startZ)*e,height:Math.sin(p*Math.PI)*7+6,p,endX:x,endZ:z}}
function drawShots(){for(const s of game.projectiles){const pos=shotPosition(s),p=project(pos.x,pos.z,pos.height),tailP=Math.max(0,pos.p-.06),tail=project(s.startX+(pos.endX-s.startX)*tailP,s.startZ+(pos.endZ-s.startZ)*tailP,pos.height);ctx.save();ctx.strokeStyle=color(s.team);ctx.shadowColor=color(s.team);ctx.shadowBlur=12;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(p.x,p.y,2.3,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawEffects(){for(const r of game.rings){const p=project(r.x,r.z),v=1-r.life/r.maxLife;ctx.save();ctx.globalAlpha=1-v;ctx.strokeStyle=color(r.color);if(r.shockwave){ctx.lineWidth=(6-v*3)*p.scale;ctx.shadowColor=color(r.color);ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(p.x,p.y,(12+v*88)*p.scale,(5+v*32)*p.scale,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=(1-v)*.75;ctx.strokeStyle="#fff7d6";ctx.lineWidth=2*p.scale;ctx.beginPath();ctx.ellipse(p.x,p.y,(7+v*64)*p.scale,(3+v*23)*p.scale,0,0,Math.PI*2);ctx.stroke()}else{ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(p.x,p.y,(8+v*38)*p.scale,(3+v*14)*p.scale,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}for(const q of game.particles){const p=project(q.x,q.z,Math.max(0,q.height));ctx.save();ctx.globalAlpha=Math.max(0,q.life/q.maxLife);ctx.fillStyle=color(q.color);ctx.beginPath();ctx.arc(p.x,p.y,q.size*p.scale,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawSpecials(now){for(const u of game.specialUnits){const target=byId(u.targetId),isGiant=u.team==="blue",img=isGiant?art.blueGiant:art.redMegalodon,p=project(u.x,u.z,isGiant?8:16),height=(isGiant?142:92)*p.scale,width=height*1.5,desired=target?Math.sign(target.x-u.x)||1:(u.team==="blue"?-1:1),baseFacing=isGiant?1:-1,flip=desired!==baseFacing;ctx.save();ctx.fillStyle="rgba(0,0,0,.42)";ctx.beginPath();ctx.ellipse(p.x,p.y+8*p.scale,width*.28,10*p.scale,0,0,Math.PI*2);ctx.fill();if(u.phase==="waiting"){ctx.strokeStyle=color(u.team);ctx.lineWidth=4;ctx.globalAlpha=.6+Math.sin(now*.01)*.25;ctx.beginPath();ctx.arc(p.x,p.y-height*.35,width*.28,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.translate(p.x,p.y);if(flip)ctx.scale(-1,1);if(u.phase==="striking"){const pulse=1+Math.sin(now*.025)*.05;ctx.scale(pulse,pulse);ctx.shadowColor=color(u.team);ctx.shadowBlur=28}if(img.complete&&img.naturalWidth)ctx.drawImage(img,-width/2,-height,width,height);ctx.restore()}}
function drawOrder(){const a=byId(game.lastOrderFriendlyId),t=byId(game.lastOrderTargetId);if(!a||!a.alive||!t||!t.alive||a.targetId!==t.id)return;const p1=project(a.x,a.z,a.kind==="tower"?14:7),p2=project(t.x,t.z,t.kind==="tower"?14:7);ctx.save();ctx.strokeStyle="rgba(255,213,106,.62)";ctx.setLineDash([7,7]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();ctx.restore()}
function render(now){const dt=Math.min(.05,Math.max(0,(now-game.lastTime)/1000));game.lastTime=now;if(game.phase==="playing")update(dt);else updateEffects(Math.min(dt,.03));const sx=game.cameraShake?(Math.random()-.5)*game.cameraShake*14:0,sy=game.cameraShake?(Math.random()-.5)*game.cameraShake*8:0;ctx.save();ctx.translate(sx,sy);drawBackground(now);drawShields(now);for(const u of game.entities.slice().sort((a,b)=>a.z-b.z))u.kind==="tower"?drawTower(u,now):drawSoldier(u,now);drawBarriers();drawShots();drawSpecials(now);drawOrder();drawEffects();ctx.restore();requestAnimationFrame(render)}
function formatTime(seconds){const n=Math.floor(seconds);return Math.floor(n/60)+":"+String(n%60).padStart(2,"0")}
function setStatus(title,text){ui.selectionTitle.textContent=title;ui.status.textContent=text}
function updateHud(){ui.blueTowers.textContent=living("blue","tower").length;ui.redTowers.textContent=living("red","tower").length;ui.matchTime.textContent=formatTime(game.elapsed);ui.matchStatus.textContent=game.world===2?"RIFT "+game.worldBattle:"BATTLE "+game.level;const t=byId(game.selectedId),selected=t&&t.alive&&t.team===game.playerTeam,valid=selected&&t.kind==="tower"&&!t.deployed;ui.deploy.disabled=!valid||game.phase!=="playing";if(!valid){game.deployArmedUntil=0;ui.deploy.classList.remove("armed");ui.deploy.textContent="Deploy Soldier"}const s=game.shields[game.playerTeam],active=game.elapsed<s.activeUntil,cooling=!active&&game.elapsed<s.readyAt;ui.shield.disabled=game.phase!=="playing"||!selected||active||cooling||s.uses<=0;ui.shield.classList.toggle("shield-ready",selected&&!active&&!cooling&&s.uses>0);ui.shield.classList.toggle("shield-active",active);ui.shield.textContent=active?"Shield "+Math.ceil(s.activeUntil-game.elapsed)+"s":cooling?"Ready "+Math.ceil(s.readyAt-game.elapsed)+"s":selected?"Shield "+t.id+" ("+s.uses+")":"Select for Shield";const special=game.specials[game.playerTeam],name=specialName(game.playerTeam),unlocked=specialUnlocked(game.playerTeam),specialActive=game.specialUnits.some(u=>u.team===game.playerTeam),target=byId(game.manualTargetId),validTarget=target&&target.alive&&target.team===game.aiTeam&&target.kind==="tower";ui.special.classList.toggle("special-ready",unlocked&&!special.used);ui.special.classList.toggle("special-active",specialActive);ui.special.disabled=game.phase!=="playing"||special.used||!unlocked;ui.special.textContent=special.used?(specialActive?name+" Active":name+" Used"):!unlocked?name+" Locked":"Deploy "+name;ui.debugUnits.textContent="Units "+living().length;ui.debugProjectiles.textContent="Shots "+game.projectiles.length;ui.debugDamage.textContent="Damage "+Math.round(game.damageDealt)}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function hitTest(pt){const hits=[];if(game.world===2)for(const u of game.barriers){if(!u.alive)continue;const g=barrierGeometry(u),dx=pt.x-g.p.x,dy=pt.y-g.p.y,c=Math.cos(-u.angle),sn=Math.sin(-u.angle),lx=dx*c-dy*sn,ly=dx*sn+dy*c;if(Math.abs(lx)<=g.w*.52&&Math.abs(ly)<=Math.max(34,g.h*.42))hits.push({u,score:Math.hypot(lx/g.w,ly/g.h),z:u.z})}for(const u of game.entities){if(!u.alive)continue;const base=project(u.x,u.z),s=base.scale;if(u.kind==="tower"){const width=Math.max(64,116*s*.8),height=Math.max(88,116*s*1.08),cx=base.x,cy=base.y-height*.46;if(Math.abs(pt.x-cx)<=width/2&&Math.abs(pt.y-cy)<=height/2)hits.push({u,score:Math.hypot((pt.x-cx)/width,(pt.y-cy)/height),z:u.z})}else{const head=project(u.x,u.z,10),width=Math.max(50,34*s),top=head.y-22,bottom=base.y+20;if(pt.x>=base.x-width/2&&pt.x<=base.x+width/2&&pt.y>=top&&pt.y<=bottom)hits.push({u,score:Math.abs(pt.x-base.x)/width,z:u.z})}}hits.sort((a,b)=>a.score-b.score||b.z-a.z);return hits.length?hits[0].u:null}
function handlePointer(e){if(game.phase!=="playing")return;e.preventDefault();ensureAudio();let u=hitTest(point(e));if(!u){game.selectedId=null;game.manualTargetId=null;game.orderFriendlyId=null;game.orderEnemyId=null;setStatus("No unit selected",game.world===2?"Tap a barrier or exposed enemy tower, then one of your units.":"Tap one of your units and one enemy target, in either order.")}else if(u.team===game.playerTeam){if(u.kind==="barrier"){game.selectedId=null;game.orderFriendlyId=null;setStatus(u.id+" barrier",Math.ceil(u.hp)+" barrier strength remaining.")}else{game.selectedId=u.id;const enemy=byId(game.orderEnemyId);if(enemy&&enemy.alive)assignTarget(enemy,u);else{game.orderFriendlyId=u.id;game.orderEnemyId=null;if(u.kind==="tower")setStatus(u.id+" selected",u.deployed?"Tap an enemy target, or shield this structure.":"Tap an enemy target, deploy its soldier, or shield it.");else setStatus(u.id+" selected","Tap an enemy barrier or tower for this soldier to pursue.");addRing(u.x,u.z,"gold",.45)}}}else{u=attackableTarget(u);const waiting=game.specialUnits.find(s=>s.team===game.playerTeam&&s.phase==="choosing");if(waiting&&(u.kind==="tower"||u.kind==="barrier")){waiting.targetId=u.id;waiting.phase="approach";waiting.progress=0;waiting.startX=waiting.x;waiting.startZ=waiting.z;game.manualTargetId=u.id;setStatus(specialName(game.playerTeam)+" targeting "+u.id,"Special attack is underway.");addRing(u.x,u.z,"red",.8)}else{const friendly=byId(game.orderFriendlyId);if(friendly&&friendly.alive&&canAttack(friendly))assignTarget(u,friendly);else{game.orderEnemyId=u.id;game.orderFriendlyId=null;game.manualTargetId=u.id;setStatus(u.id+" selected",u.kind==="barrier"?"Now tap one of your armed towers or walking soldiers to breach it.":"Now tap one of your armed towers or walking soldiers.");addRing(u.x,u.z,"red",.7)}}}updateHud()}
for(const b of document.querySelectorAll(".team-choice"))b.addEventListener("click",()=>{game.playerTeam=b.dataset.team;for(const p of document.querySelectorAll(".team-choice"))p.classList.toggle("selected",p===b);resetMatch()});
for(const b of document.querySelectorAll(".difficulty"))b.addEventListener("click",()=>{game.difficulty=b.dataset.difficulty;for(const p of document.querySelectorAll(".difficulty"))p.classList.toggle("selected",p===b)});
ui.start.addEventListener("click",startMatch);ui.level2.addEventListener("click",startLevel2);ui.restart.addEventListener("click",continueBattle);ui.pause.addEventListener("click",pauseGame);ui.resume.addEventListener("click",resumeGame);ui.deploy.addEventListener("click",handleDeploy);ui.shield.addEventListener("click",()=>activateShield(game.playerTeam,game.selectedId));ui.special.addEventListener("click",()=>deploySpecial(game.playerTeam));for(const b of document.querySelectorAll(".menu-button"))b.addEventListener("click",showMainMenu);canvas.addEventListener("pointerdown",handlePointer,{passive:false});window.addEventListener("resize",resizeCanvas);if(window.visualViewport)window.visualViewport.addEventListener("resize",resizeCanvas);window.addEventListener("keydown",e=>{if(e.key==="Escape"){if(game.phase==="playing")pauseGame();else if(game.phase==="paused")resumeGame()}if(e.code==="Space"&&game.phase==="playing"){e.preventDefault();activateShield(game.playerTeam,game.selectedId)}if(e.key.toLowerCase()==="d")ui.debugPanel.classList.toggle("hidden")});
resetMatch();resizeCanvas();requestAnimationFrame(render);
