"use strict";
const canvas=document.getElementById("game-canvas"),ctx=canvas.getContext("2d"),$=id=>document.getElementById(id);
const ui={battleHud:$("battle-hud"),commandBar:$("command-bar"),mainMenu:$("main-menu"),pauseMenu:$("pause-menu"),resultMenu:$("result-menu"),stageBriefing:$("stage-briefing"),stageKicker:$("stage-briefing-kicker"),stageTitle:$("stage-briefing-title"),stageFeatures:$("stage-feature-list"),stageStart:$("stage-start-button"),testLock:$("test-lock-button"),testLockIcon:$("test-lock-icon"),testActions:$("test-level-actions"),status:$("status"),selectionTitle:$("selection-title"),deploy:$("deploy-button"),shield:$("shield-button"),blueTowers:$("blue-towers"),redTowers:$("red-towers"),matchTime:$("match-time"),matchStatus:$("match-status"),pause:$("pause-button"),start:$("start-button"),level2:$("level-2-button"),level3:$("level-3-button"),layout2:$("layout-2-button"),layout3:$("layout-3-button"),layoutToolbar:$("layout-toolbar"),layoutTitle:$("layout-title"),layoutMessage:$("layout-message"),layoutReset:$("layout-reset-button"),layoutCopy:$("layout-copy-button"),layoutTest:$("layout-test-button"),layoutMenu:$("layout-menu-button"),resume:$("resume-button"),restart:$("restart-button"),resultTitle:$("result-title"),resultKicker:$("result-kicker"),resultDetail:$("result-detail"),debugPanel:$("debug-panel"),special:$("special-button"),debugUnits:$("debug-units"),debugProjectiles:$("debug-projectiles"),debugDamage:$("debug-damage")};
const C={towerHp:150,towerDamage:12,towerRate:1,soldierHp:150,soldierDamage:10,soldierRate:.85,soldierSpeed:3.4,soldierRange:12,smashRange:2.8,smashDamage:55,smashRate:1.15,shieldUses:3,shieldDuration:5,shieldCooldown:10,shotSpeed:48,barrierHp:240,specialApproach:2.4,specialStrike:0.5,reactorCaptureRange:2.4,reactorFireBoost:.75,reactorShieldBonus:3,stormWarning:3,stormActive:5,stormInterval:18,worldWidth:50,worldDepth:72};
const levels={easy:{delay:1.9,aim:.45,shield:.42,fireRate:1.8,deploy:[Infinity,Infinity]},medium:{delay:1.1,aim:.72,shield:.68,fireRate:1.4,deploy:[7,11]},hard:{delay:.55,aim:.95,shield:.9,fireRate:1,deploy:[3.5,6]}};
let audio=null,lastImpact=0,viewport={w:1,h:1,dpr:1};
const game={phase:"menu",difficulty:"medium",playerTeam:"blue",aiTeam:"red",world:1,worldBattle:1,level:1,startingTowers:3,lastResult:null,elapsed:0,lastTime:performance.now(),selectedId:null,manualTargetId:null,orderFriendlyId:null,orderEnemyId:null,orderReactor:false,lastOrderFriendlyId:null,lastOrderTargetId:null,deployArmedUntil:0,entities:[],barriers:[],projectiles:[],particles:[],rings:[],specialUnits:[],reactor:null,storm:null,damageDealt:0,nextSoldier:1,nextShot:1,cameraShake:0,aiAt:0,aiDeployAt:Infinity,layoutDrag:null,shields:{},specials:{}};
const art={background:new Image(),riftBackground:new Image(),stormBackground:new Image(),blueTower:new Image(),redTower:new Image(),blueGiant:new Image(),redMegalodon:new Image(),blueBarrier:new Image(),redBarrier:new Image(),destroyedBarrier:new Image()};art.background.src="assets/alien-battlefield.png";art.riftBackground.src="assets/world2-rift-background.png";art.stormBackground.src="assets/world3-storm-reactor-background.png";art.blueTower.src="assets/blue-tower.png";art.redTower.src="assets/red-tower.png";art.blueGiant.src="assets/blue-giant.png";art.redMegalodon.src="assets/red-megalodon.png";art.blueBarrier.src="assets/world2-shield-blue.png";art.redBarrier.src="assets/world2-shield-red.png";art.destroyedBarrier.src="assets/world2-shield-destroyed.png";
function loadImage(src){const image=new Image();image.src=src;return image}
const soldierArt={blue:{walkAway:[loadImage("assets/soldiers/blue-walk-away.png"),loadImage("assets/soldiers/blue-walk-away-2.png"),loadImage("assets/soldiers/blue-walk-away-3.png")],walkSide:[loadImage("assets/soldiers/blue-walk-side.png"),loadImage("assets/soldiers/blue-walk-side-2.png"),loadImage("assets/soldiers/blue-walk-side-3.png")],attackFire:loadImage("assets/soldiers/blue-attack-fire.png"),attackSmash:loadImage("assets/soldiers/blue-attack-smash.png")},red:{walkAway:[loadImage("assets/soldiers/red-walk-away.png"),loadImage("assets/soldiers/red-walk-away-2.png"),loadImage("assets/soldiers/red-walk-away-3.png")],walkSide:[loadImage("assets/soldiers/red-walk-side.png"),loadImage("assets/soldiers/red-walk-side-2.png"),loadImage("assets/soldiers/red-walk-side-3.png")],attackFire:loadImage("assets/soldiers/red-attack-fire.png"),attackSmash:loadImage("assets/soldiers/red-attack-smash.png")}};

function tower(id,team,x,z){return{id,team,kind:"tower",x,z,hp:C.towerHp,maxHp:C.towerHp,alive:true,deployed:false,rearmStartedAt:0,weaponReadyAt:0,targetId:null,nextFire:Math.random()*.45+.35,nextSmash:0,orderedUntil:0,hitFlash:0,shieldUntil:0}}
function formation(count,near){const rowCount=Math.max(2,Math.ceil(count/5)),zMin=7,zMax=32,base=Math.floor(count/rowCount),extra=count%rowCount,counts=Array.from({length:rowCount},(_,row)=>base+(row<extra?1:0)),result=[];for(let row=0;row<rowCount;row++){const columns=counts[row],spacing=columns===1?0:Math.min(12,32/(columns-1));let start=row,end=row;while(start>0&&counts[start-1]===columns)start--;while(end<rowCount-1&&counts[end+1]===columns)end++;const groupLength=end-start+1,offsets=groupLength===2?[-3,3]:groupLength===3?[-3,3,0]:[-3,3,-1.5,1.5,0],shift=groupLength>1?offsets[(row-start)%offsets.length]:0,z=zMin+(zMax-zMin)*row/(rowCount-1);for(let column=0;column<columns;column++){const x=(column-(columns-1)/2)*spacing+shift;result.push({x,z:near?z:-z})}}return result}
const DEFAULT_RIFT_LAYOUT={
  slots:{nearPlateau:[[.2324,.4494],[.3083,.5064],[.1932,.5864],[.1689,.4303],[.1304,.5480],[.0951,.4418]],nearLow:[[.5201,.7551],[.6276,.8443],[.4598,.9031],[.3555,.8808],[.5646,.8787],[.4049,.7922]],farPlateau:[[.5579,.2507],[.6128,.2829],[.6715,.2539],[.6345,.2155],[.7172,.2451],[.5896,.2062]],farLow:[[.7837,.4431],[.8510,.5049],[.8267,.3904],[.8965,.4473],[.8625,.3409],[.9274,.3665]]},
  barriers:{nearPlateau:{nx:.3557,ny:.3674,width:.25,angle:.5188},nearLow:{nx:.6441,ny:.6412,width:.28,angle:.5727},farPlateau:{nx:.5082,ny:.2875,width:.23,angle:.4519},farLow:{nx:.7760,ny:.5223,width:.27,angle:.4753}}
};
const RIFT_GROUPS=["nearPlateau","nearLow","farPlateau","farLow"];
function freshRiftLayout(){return JSON.parse(JSON.stringify(DEFAULT_RIFT_LAYOUT))}
function validRiftLayout(data){if(!data||!data.slots||!data.barriers)return false;const points=RIFT_GROUPS.flatMap(group=>Array.isArray(data.slots[group])?data.slots[group]:[]),barriers=RIFT_GROUPS.map(group=>data.barriers[group]);return RIFT_GROUPS.every(group=>Array.isArray(data.slots[group])&&data.slots[group].length===6)&&points.length===24&&points.every(p=>Array.isArray(p)&&p.length===2&&p.every(v=>Number.isFinite(v)&&v>=0&&v<=1))&&barriers.every(b=>b&&Number.isFinite(b.nx)&&Number.isFinite(b.ny)&&Number.isFinite(b.width)&&Number.isFinite(b.angle)&&b.nx>=0&&b.nx<=1&&b.ny>=0&&b.ny<=1&&b.width>0)}
function readRiftLayout(){try{const data=JSON.parse(localStorage.getItem("towerBattleRiftLayout"));return validRiftLayout(data)?data:freshRiftLayout()}catch{return freshRiftLayout()}}
let activeRiftLayout=readRiftLayout(),RIFT_SLOTS=activeRiftLayout.slots,RIFT_BARRIER_SPECS=activeRiftLayout.barriers;
function mapPosition(nx,ny){return{x:(nx-.5)*C.worldWidth,z:(ny-.5)*C.worldDepth}}
function riftTowersPerBarrier(){return Math.min(6,game.worldBattle+1)}
function barrier(id,team,group,spec){const p=mapPosition(spec.nx,spec.ny);return{id,team,kind:"barrier",group,x:p.x,z:p.z,hp:C.barrierHp,maxHp:C.barrierHp,alive:true,hitFlash:0,mapWidth:spec.width,angle:spec.angle}}
function addRiftSide(team,prefix,groups,count){let number=1;for(const group of groups){const barrierId=prefix+"-"+(group.includes("Plateau")?"P":"L");game.barriers.push(barrier(barrierId,team,group,RIFT_BARRIER_SPECS[group]));for(const slot of RIFT_SLOTS[group].slice(0,count)){const p=mapPosition(slot[0],slot[1]),t=tower(prefix+(number++),team,p.x,p.z);t.barrierId=barrierId;t.riftGroup=group;game.entities.push(t)}}}
function setupOpenField(){game.startingTowers=game.level+2;const near=game.playerTeam,far=game.aiTeam,np=near==="blue"?"B":"R",fp=far==="blue"?"B":"R",nearSlots=formation(game.startingTowers,true),farSlots=formation(game.startingTowers,false);nearSlots.forEach((p,i)=>game.entities.push(tower(np+(i+1),near,p.x,p.z)));farSlots.forEach((p,i)=>game.entities.push(tower(fp+(i+1),far,p.x,p.z)))}
function setupRift(){const count=riftTowersPerBarrier(),near=game.playerTeam,far=game.aiTeam,np=near==="blue"?"B":"R",fp=far==="blue"?"B":"R";game.startingTowers=count*2;addRiftSide(near,np,["nearPlateau","nearLow"],count);addRiftSide(far,fp,["farPlateau","farLow"],count)}
// Every slot is normalized so hand-placed layouts stay attached to the art.
const DEFAULT_STORM_LAYOUT={
  lanes:[
    {name:"UPPER",near:[[.1537,.4237],[.2171,.3837],[.2819,.3437],[.3519,.3012]],far:[[.7082,.1006],[.6493,.1289],[.5815,.1659],[.5193,.2055]]},
    {name:"CENTER",near:[[.0753,.6833],[.1568,.6209],[.2382,.5635],[.3146,.5036]],far:[[.8094,.1514],[.7593,.1921],[.7113,.2192],[.6531,.2587]]},
    {name:"LOWER",near:[[.2035,.8659],[.2696,.8011],[.3371,.7512],[.4193,.6889]],far:[[.8656,.2644],[.8146,.3226],[.7657,.3708],[.7047,.4239]]}
  ],
  reactor:[.5133,.42]
};
function freshStormLayout(){return JSON.parse(JSON.stringify(DEFAULT_STORM_LAYOUT))}
function validStormLayout(data){if(!data||!Array.isArray(data.lanes)||data.lanes.length!==3||!Array.isArray(data.reactor)||data.reactor.length!==2)return false;const points=data.lanes.flatMap(l=>Array.isArray(l.near)&&Array.isArray(l.far)?l.near.concat(l.far):[]);return points.length===24&&points.concat([data.reactor]).every(p=>Array.isArray(p)&&p.length===2&&p.every(v=>Number.isFinite(v)&&v>=0&&v<=1))}
function readStormLayout(){try{const data=JSON.parse(localStorage.getItem("towerBattleStormLayout"));return validStormLayout(data)?data:freshStormLayout()}catch{return freshStormLayout()}}
let activeStormLayout=readStormLayout(),STORM_LANES=activeStormLayout.lanes,STORM_REACTOR=activeStormLayout.reactor;
function stormTowerCount(){return Math.min(12,8+game.worldBattle)}
function setupStormReactor(){const count=stormTowerCount(),allocation=[3,3,3];for(let i=9;i<count;i++)allocation[(i-9)%3]++;const near=game.playerTeam,far=game.aiTeam,np=near==="blue"?"B":"R",fp=far==="blue"?"B":"R";game.startingTowers=count;let nearNumber=1,farNumber=1;for(let lane=0;lane<STORM_LANES.length;lane++){for(const slot of STORM_LANES[lane].near.slice(0,allocation[lane])){const p=mapPosition(slot[0],slot[1]),t=tower(np+(nearNumber++),near,p.x,p.z);t.lane=lane;game.entities.push(t)}for(const slot of STORM_LANES[lane].far.slice(0,allocation[lane])){const p=mapPosition(slot[0],slot[1]),t=tower(fp+(farNumber++),far,p.x,p.z);t.lane=lane;game.entities.push(t)}}const reactorPosition=mapPosition(STORM_REACTOR[0],STORM_REACTOR[1]);game.reactor={id:"REACTOR",kind:"reactor",x:reactorPosition.x,z:reactorPosition.z,team:null,controllerId:null,alive:true,captureFlash:0};game.storm={phase:"idle",lane:-1,lastLane:-1,nextAt:15,until:0}}
function aiDeployDelay(){const [min,max]=levels[game.difficulty].deploy;return Number.isFinite(min)?min+(max-min)*Math.random():Infinity}
function resetMatch(){game.aiTeam=game.playerTeam==="blue"?"red":"blue";Object.assign(game,{elapsed:0,selectedId:null,manualTargetId:null,orderFriendlyId:null,orderEnemyId:null,orderReactor:false,lastOrderFriendlyId:null,lastOrderTargetId:null,deployArmedUntil:0,barriers:[],projectiles:[],particles:[],rings:[],specialUnits:[],reactor:null,storm:null,damageDealt:0,nextSoldier:1,nextShot:1,cameraShake:0,aiAt:.8,aiDeployAt:aiDeployDelay(),shields:{blue:{uses:3,activeUntil:0,readyAt:0},red:{uses:3,activeUntil:0,readyAt:0}},specials:{blue:{used:false},red:{used:false}}});game.entities=[];if(game.world===3)setupStormReactor();else if(game.world===2)setupRift();else setupOpenField();setStatus("No unit selected",game.world===3?"Deploy a soldier to capture the central reactor, or focus fire on an enemy tower.":game.world===2?"Break an enemy barrier to expose the towers behind it.":"Select one of your units and an enemy target, in either order.");updateHud()}
const STAGE_BRIEFINGS={
  2:{title:"The Rift",features:[["Energy Barriers","Each barrier absorbs attacks aimed at the towers behind it. Destroy that barrier to expose its protected group."],["Two Defensive Zones","Plateau and lowland towers are protected separately. Choose which defense to breach first."],["Growing Garrisons","Each Rift victory adds one tower behind every barrier, up to six towers per group."]]},
  3:{title:"Storm Reactor",features:[["Central Reactor","Send a soldier to capture it. While controlled, your towers fire 25% faster and shields recharge three seconds sooner."],["Lane Storms","A three-second warning marks the affected lane, then its towers stop firing for five seconds. Soldiers, shields, and specials still work."],["Three-Lane Front","The battle begins with three towers in each lane. Later victories add towers across the lanes, up to twelve per team."]]}
};
function setTestingUnlocked(unlocked){ui.testActions.classList.toggle("hidden",!unlocked);ui.testLock.setAttribute("aria-pressed",String(unlocked));ui.testLock.setAttribute("aria-label",unlocked?"Lock testing controls":"Unlock testing controls");ui.testLock.title=unlocked?"Lock testing controls":"Unlock testing controls";ui.testLockIcon.textContent=String.fromCodePoint(unlocked?0x1f513:0x1f512)}
function toggleTestingControls(){setTestingUnlocked(ui.testActions.classList.contains("hidden"))}
function populateStageFeatures(features){ui.stageFeatures.replaceChildren();for(const feature of features){const row=document.createElement("div"),mark=document.createElement("span"),copy=document.createElement("div"),title=document.createElement("strong"),text=document.createElement("span");row.className="stage-feature";mark.className="stage-feature-mark";title.textContent=feature[0];text.textContent=feature[1];copy.append(title,text);row.append(mark,copy);ui.stageFeatures.append(row)}}
function prepareMatch(){if(game.world<2)return startMatch();resetMatch();game.phase="briefing";game.layoutDrag=null;game.lastTime=performance.now();const briefing=STAGE_BRIEFINGS[game.world];ui.stageKicker.textContent=game.world===2?"WORLD 2 - RIFT BATTLE "+game.worldBattle:"WORLD 3 - STORM BATTLE "+game.worldBattle;ui.stageTitle.textContent=briefing.title;populateStageFeatures(briefing.features);ui.mainMenu.classList.add("hidden");ui.pauseMenu.classList.add("hidden");ui.resultMenu.classList.add("hidden");ui.layoutToolbar.classList.add("hidden");ui.battleHud.classList.add("hidden");ui.commandBar.classList.add("hidden");ui.stageBriefing.classList.remove("hidden");setTestingUnlocked(false)}
function startMatch(){resetMatch();game.phase="playing";game.layoutDrag=null;game.lastTime=performance.now();ui.mainMenu.classList.add("hidden");ui.pauseMenu.classList.add("hidden");ui.resultMenu.classList.add("hidden");ui.stageBriefing.classList.add("hidden");ui.layoutToolbar.classList.add("hidden");ui.battleHud.classList.remove("hidden");ui.commandBar.classList.remove("hidden");ensureAudio();sound("start")}
function startLevel2(){game.world=2;game.worldBattle=1;game.lastResult=null;prepareMatch()}
function startLevel3(){game.world=3;game.worldBattle=1;game.lastResult=null;prepareMatch()}
function openLayoutEditor(world,battle,title,message){game.world=world;game.worldBattle=battle;game.lastResult=null;resetMatch();game.phase="layout";game.layoutDrag=null;ui.mainMenu.classList.add("hidden");ui.pauseMenu.classList.add("hidden");ui.resultMenu.classList.add("hidden");ui.stageBriefing.classList.add("hidden");ui.battleHud.classList.add("hidden");ui.commandBar.classList.add("hidden");ui.layoutToolbar.classList.remove("hidden");ui.layoutTitle.textContent=title;ui.layoutMessage.textContent=message}
function startRiftLayoutEditor(){openLayoutEditor(2,5,"LEVEL 2 PLACEMENT","Drag all towers and energy shields into position.")}
function startStormLayoutEditor(){openLayoutEditor(3,4,"LEVEL 3 PLACEMENT","Drag every tower and the reactor into position.")}
function showMainMenu(){game.phase="menu";game.world=1;game.worldBattle=1;game.level=1;game.lastResult=null;resetMatch();ui.mainMenu.classList.remove("hidden");ui.pauseMenu.classList.add("hidden");ui.resultMenu.classList.add("hidden");ui.stageBriefing.classList.add("hidden");ui.battleHud.classList.add("hidden");ui.commandBar.classList.add("hidden");ui.layoutToolbar.classList.add("hidden");setTestingUnlocked(false)}
function pauseGame(){if(game.phase!=="playing")return;game.phase="paused";ui.pauseMenu.classList.remove("hidden")}
function resumeGame(){if(game.phase!=="paused")return;game.phase="playing";game.lastTime=performance.now();ui.pauseMenu.classList.add("hidden")}
function endMatch(result){if(game.phase!=="playing")return;game.phase="result";game.lastResult=result;ui.resultMenu.classList.remove("hidden");const world1Clear=result==="victory"&&game.world===1&&game.level===18,world2Clear=result==="victory"&&game.world===2&&game.worldBattle>=5,world3Clear=result==="victory"&&game.world===3&&game.worldBattle>=4;ui.resultKicker.textContent=world1Clear?"WORLD 1 CLEARED":world2Clear?"WORLD 2 CLEARED":world3Clear?"WORLD 3 CLEARED":result==="victory"?"ENEMY NETWORK DESTROYED":result==="defeat"?game.playerTeam.toUpperCase()+" NETWORK LOST":"STALEMATE";ui.resultTitle.textContent=world1Clear?"The Rift Awaits":world2Clear?"Storm Reactor Awaits":world3Clear?"Final Boss Awaits":result==="victory"?"Victory":result==="defeat"?"Defeat":"Draw";if(result==="victory"){if(world1Clear)ui.resultDetail.textContent="The next battle begins World 2 with two towers behind each energy barrier.";else if(world2Clear)ui.resultDetail.textContent="World 3 opens with three battle lanes and a capturable storm reactor.";else if(world3Clear)ui.resultDetail.textContent="The storm arena is cleared. The opposing faction boss is waiting in the final arena.";else if(game.world===1)ui.resultDetail.textContent="Battle "+game.level+" cleared. The next battle has "+(game.startingTowers+1)+" towers per team.";else if(game.world===2)ui.resultDetail.textContent="Rift battle "+game.worldBattle+" cleared. One tower will be added behind every barrier.";else ui.resultDetail.textContent=stormTowerCount()<12?"Storm battle "+game.worldBattle+" cleared. One tower will be added to the next lane.":"Storm battle "+game.worldBattle+" cleared. The arena remains at twelve towers per team."}else if(result==="defeat")ui.resultDetail.textContent=game.world===1?"Replay battle "+game.level+" with "+game.startingTowers+" towers per team.":game.world===2?"Replay Rift battle "+game.worldBattle+" with "+riftTowersPerBarrier()+" towers behind each barrier.":"Replay Storm battle "+game.worldBattle+" with "+stormTowerCount()+" towers per team.";else ui.resultDetail.textContent="Neither force can damage the remaining structures.";ui.restart.textContent=result==="victory"?(world1Clear?"Enter World 2":world2Clear?"Enter World 3":world3Clear?"Face Final Boss":"Next Battle"):"Replay Battle";sound(result==="victory"?"victory":"defeat")}
function continueBattle(){if(game.lastResult==="victory"){if(game.world===3&&game.worldBattle>=4){location.href="level4.html?team="+game.playerTeam+"&difficulty="+game.difficulty;return}if(game.world===1&&game.level>=18){game.world=2;game.worldBattle=1}else if(game.world===1)game.level++;else if(game.world===2&&game.worldBattle>=5){game.world=3;game.worldBattle=1}else game.worldBattle++}prepareMatch()}
function ensureAudio(){if(audio){if(audio.state==="suspended")audio.resume();return}const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A}
function sound(type){if(!audio)return;const now=audio.currentTime;if(type==="impact"&&now-lastImpact<.08)return;if(type==="impact")lastImpact=now;const map={start:[220,440,.18,.05],shoot:[390,190,.07,.012],impact:[150,80,.09,.025],shield:[180,520,.35,.045],explode:[95,38,.28,.07],victory:[330,660,.65,.055],defeat:[180,65,.55,.05]},v=map[type]||map.impact,o=audio.createOscillator(),g=audio.createGain();o.type=type==="impact"||type==="explode"?"sawtooth":"sine";o.frequency.setValueAtTime(v[0],now);o.frequency.exponentialRampToValueAtTime(v[1],now+v[2]);g.gain.setValueAtTime(v[3],now);g.gain.exponentialRampToValueAtTime(.0001,now+v[2]);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+v[2])}
function byId(id){return game.entities.find(e=>e.id===id)||game.barriers.find(e=>e.id===id)||(game.reactor&&game.reactor.id===id?game.reactor:null)}
function activeBarrierFor(target){return target&&target.kind==="tower"&&target.barrierId?game.barriers.find(b=>b.id===target.barrierId&&b.alive):null}
function structureTargets(team){const barriers=game.barriers.filter(b=>b.alive&&b.team===team),towers=living(team,"tower").filter(t=>!activeBarrierFor(t));return barriers.concat(towers)}
function attackableTarget(target){return activeBarrierFor(target)||target}
function living(team,kind){return game.entities.filter(e=>e.alive&&(!team||e.team===team)&&(!kind||e.kind===kind))}
function weaponOffline(e){return e.kind==="tower"&&e.deployed&&game.elapsed<e.weaponReadyAt}
function towerStormDisabled(e){return game.world===3&&game.storm&&game.storm.phase==="active"&&e.kind==="tower"&&e.lane===game.storm.lane}
function canOrder(e){return e.alive&&(e.kind==="soldier"||!weaponOffline(e))}
function canAttack(e){return canOrder(e)&&!towerStormDisabled(e)}
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function autoTarget(a){const enemyTeam=a.team==="blue"?"red":"blue",enemies=living(enemyTeam),soldiers=enemies.filter(e=>e.kind==="soldier"),structures=structureTargets(enemyTeam);let pool=soldiers.length?soldiers:structures;if(!pool.length)return null;if(a.kind==="soldier"&&!soldiers.length){pool.sort((x,y)=>dist(a,x)-dist(a,y));return pool[0]}if(a.team===game.aiTeam&&Math.random()>levels[game.difficulty].aim)return pool[Math.floor(Math.random()*pool.length)];pool.sort((x,y)=>{const damaged=x.hp/x.maxHp-y.hp/y.maxHp;return Math.abs(damaged)>.18?damaged:dist(a,x)-dist(a,y)});return pool[0]}
function assignTarget(target,attacker){if(!target||!attacker||attacker.team!==game.playerTeam||!canOrder(attacker))return false;attacker.targetId=target.id;attacker.reactorOrder=false;attacker.holdingReactor=false;attacker.orderedUntil=Number.MAX_VALUE;game.manualTargetId=target.id;game.lastOrderFriendlyId=attacker.id;game.lastOrderTargetId=target.id;game.orderFriendlyId=null;game.orderEnemyId=null;game.orderReactor=false;setStatus(attacker.id+" focusing "+target.id,attacker.kind==="soldier"?"Soldier will fire while advancing and smash the target at close range.":"This tower will keep firing at the selected target.");addRing(attacker.x,attacker.z,"gold",.5);addRing(target.x,target.z,"red",.7);return true}
function spawnSoldier(t,announce=t.team===game.playerTeam){t.deployed=true;t.weaponReadyAt=Infinity;t.targetId=null;const spawnZ=game.world===3?t.z+(t.team===game.playerTeam?-2.5:2.5):t.z-2.5,s={id:(t.team==="blue"?"B-S":"R-S")+game.nextSoldier++,team:t.team,kind:"soldier",sourceTowerId:t.id,x:t.x,z:spawnZ,hp:C.soldierHp,maxHp:C.soldierHp,alive:true,targetId:null,reactorOrder:false,holdingReactor:false,nextFire:game.elapsed,nextSmash:game.elapsed,orderedUntil:0,hitFlash:0,shieldUntil:0};game.entities.push(s);if(announce){game.selectedId=s.id;game.deployArmedUntil=0;setStatus(s.id+" deployed",game.world===3?"Tap the central reactor to capture it, or tap an enemy tower.":t.id+"'s weapon is offline while its soldier is active.")}burst(t.x,spawnZ,t.team,16);addRing(t.x,t.z,t.team,.9);sound("start");updateHud();return s}
function handleDeploy(){const t=byId(game.selectedId);if(!t||t.team!==game.playerTeam||t.kind!=="tower"||!t.alive||t.deployed)return;spawnSoldier(t)}
function activateShield(team,targetId){const s=game.shields[team],target=byId(targetId);if(!target||!target.alive||target.team!==team||target.kind==="barrier"||target.kind==="reactor"){if(team===game.playerTeam)setStatus("Select a unit first","Select one of your towers or walking soldiers, then activate its shield.");return false}if(s.uses<=0||game.elapsed<s.activeUntil||game.elapsed<s.readyAt)return false;s.uses--;s.activeUntil=game.elapsed+C.shieldDuration;const reactorBonus=game.world===3&&game.reactor&&game.reactor.team===team?C.reactorShieldBonus:0;s.readyAt=s.activeUntil+C.shieldCooldown-reactorBonus;target.shieldUntil=s.activeUntil;addRing(target.x,target.z,team,1.2);if(team===game.playerTeam)setStatus(target.id+" shielded",reactorBonus?"Reactor power shortens this shield cooldown by three seconds.":"This unit blocks all incoming damage for five seconds.");sound("shield");updateHud();return true}
function shielded(target){return game.elapsed<(target.shieldUntil||0)}
function fire(a,t){const reactorRate=game.world===3&&game.reactor&&game.reactor.team===a.team&&a.kind==="tower"?C.reactorFireBoost:1,rate=(a.kind==="tower"?C.towerRate:C.soldierRate)*levels[game.difficulty].fireRate*reactorRate,damage=a.kind==="tower"?C.towerDamage:C.soldierDamage;a.nextFire=game.elapsed+rate;game.projectiles.push({id:game.nextShot++,sourceId:a.id,targetId:t.id,team:a.team,startX:a.x,startZ:a.z,startAt:game.elapsed,duration:Math.max(.22,dist(a,t)/C.shotSpeed),damage});burst(a.x,a.z,a.team,3);if(Math.random()<.35)sound("shoot")}
function hit(target,damage,team){if(!target.alive)return;const blocker=activeBarrierFor(target);if(blocker)return hit(blocker,damage,team);if(shielded(target)){addRing(target.x,target.z,target.team,.34);burst(target.x,target.z,target.team,5);return}target.hp=Math.max(0,target.hp-damage);target.hitFlash=.12;if(team===game.playerTeam)game.damageDealt+=damage;burst(target.x,target.z,target.team==="blue"?"red":"blue",7);sound("impact");if(target.hp<=0)destroy(target)}
function destroy(e){e.alive=false;e.targetId=null;const wasController=game.reactor&&game.reactor.controllerId===e.id;if(wasController){game.reactor.controllerId=null;game.reactor.team=null;game.reactor.captureFlash=1;addRing(game.reactor.x,game.reactor.z,"gold",1);if(e.team===game.playerTeam)setStatus("Reactor lost","Your controlling soldier was destroyed. The reactor is neutral again.");else setStatus("Reactor neutral","The enemy controller was destroyed. Send a soldier to capture it.")}game.cameraShake=e.kind==="barrier"?.7:e.kind==="tower"?.45:.18;burst(e.x,e.z,"fire",e.kind==="barrier"?48:e.kind==="tower"?36:14);addRing(e.x,e.z,"fire",.9);if(e.kind==="tower"||e.kind==="barrier")sound("explode");if(e.kind==="barrier"&&e.team!==game.playerTeam)setStatus(e.id+" breached","The towers behind this barrier are exposed.");if(e.kind==="soldier"&&e.sourceTowerId){const source=byId(e.sourceTowerId);if(source&&source.alive){source.rearmStartedAt=game.elapsed;source.weaponReadyAt=source.rearmStartedAt+3;source.nextFire=source.weaponReadyAt;if(!wasController)setStatus(e.id+" destroyed",source.id+" will resume firing in 3 seconds.")}}if(game.selectedId===e.id){game.selectedId=null;if(e.kind!=="soldier"||!e.sourceTowerId)setStatus("Unit destroyed","Select another tower or tap an enemy to redirect fire.")}for(const u of game.entities)if(u.targetId===e.id)u.targetId=null;updateHud()}
function updateCombat(dt){for(const u of game.entities){if(u.hitFlash>0)u.hitFlash-=dt;if(!u.alive||!canAttack(u))continue;let t=byId(u.targetId);if(!t||!t.alive||(t.team===u.team&&t.kind!=="reactor")){if(u.kind==="soldier"&&u.reactorOrder&&game.reactor)t=game.reactor;else{t=autoTarget(u);u.reactorOrder=false}u.targetId=t?t.id:null;u.orderedUntil=0}if(u.kind==="soldier"&&u.holdingReactor){if(!game.reactor||game.reactor.controllerId!==u.id){u.holdingReactor=false;u.reactorOrder=false}else{u.x=game.reactor.x+(u.team===game.playerTeam?-1.1:1.1);u.z=game.reactor.z+(u.team===game.playerTeam?1.1:-1.1);const enemyTeam=u.team==="blue"?"red":"blue",threat=living(enemyTeam,"soldier").sort((a,b)=>dist(u,a)-dist(u,b))[0];if(threat&&dist(u,threat)<=C.soldierRange&&game.elapsed>=u.nextFire)fire(u,threat);continue}}if(!t)continue;if(u.kind==="soldier"&&u.reactorOrder&&game.reactor){const controller=reactorController();if(controller&&controller.team!==u.team)t=controller;else if(!controller){const range=dist(u,game.reactor);if(range<=C.reactorCaptureRange){captureReactor(u);continue}const dx=game.reactor.x-u.x,dz=game.reactor.z-u.z,len=Math.max(.001,Math.hypot(dx,dz));u.x+=dx/len*C.soldierSpeed*dt;u.z+=dz/len*C.soldierSpeed*dt;continue}else{u.reactorOrder=false;t=autoTarget(u);u.targetId=t?t.id:null}}if(!t)continue;if(u.kind==="soldier"){const range=dist(u,t),canSmash=(t.kind==="tower"||t.kind==="barrier")&&range<=C.smashRange;if(canSmash){if(game.elapsed>=u.nextSmash){u.nextSmash=game.elapsed+C.smashRate;game.cameraShake=.38;addShockwave(t.x,t.z,u.team);burst(t.x,t.z,"fire",22);hit(t,C.smashDamage,u.team);sound("explode")}}else{if(range>C.smashRange){const dx=t.x-u.x,dz=t.z-u.z,len=Math.max(.001,Math.hypot(dx,dz));u.x+=dx/len*C.soldierSpeed*dt;u.z+=dz/len*C.soldierSpeed*dt}if(game.elapsed>=u.nextFire)fire(u,t)}}else if(game.elapsed>=u.nextFire)fire(u,t)}for(let i=game.projectiles.length-1;i>=0;i--){const s=game.projectiles[i];if(game.elapsed-s.startAt>=s.duration){const t=byId(s.targetId);if(t&&t.alive&&t.kind!=="reactor")hit(t,s.damage,s.team);game.projectiles.splice(i,1)}}}
function specialName(team){return team==="blue"?"Giant":"Megalodon"}
function specialUnlocked(team){return living(team,"tower").length<game.startingTowers}
function deploySpecial(team,targetId=null){const state=game.specials[team],target=targetId?byId(targetId):null;if(!state||state.used||!specialUnlocked(team))return false;if(targetId&&(!target||!target.alive||target.team===team||(target.kind!=="tower"&&target.kind!=="barrier")))return false;state.used=true;const start=game.world>=2?mapPosition(team===game.playerTeam?.10:.90,team===game.playerTeam?.90:.12):{x:team==="blue"?-12:14,z:team===game.playerTeam?34:-34},startZ=start.z,startX=start.x;game.specialUnits.push({team,targetId:target?target.id:null,phase:target?"approach":"choosing",x:startX,z:startZ,startX,startZ,progress:0,timer:0});if(team===game.playerTeam)setStatus(specialName(team)+" deployed",target?specialName(team)+" is heading for "+target.id+".":(game.world===2?"Tap the enemy barrier or exposed tower ":"Tap the enemy tower ")+specialName(team)+" should destroy.");sound("start");updateHud();return true}
function retargetSpecial(unit){const targets=structureTargets(unit.team===game.playerTeam?game.aiTeam:game.playerTeam);if(!targets.length)return null;targets.sort((a,b)=>dist(unit,a)-dist(unit,b));unit.targetId=targets[0].id;unit.phase="approach";unit.progress=0;unit.startX=unit.x;unit.startZ=unit.z;if(unit.team===game.playerTeam)setStatus(specialName(unit.team)+" retargeting","Original target lost. Switching to "+targets[0].id+".");return targets[0]}
function specialEdge(unit,target){const dx=unit.startX-target.x,dz=unit.startZ-target.z,len=Math.max(.001,Math.hypot(dx,dz));return{x:target.x+dx/len*4.4,z:target.z+dz/len*4.4}}
function updateSpecials(dt){for(let i=game.specialUnits.length-1;i>=0;i--){const u=game.specialUnits[i];if(u.phase==="choosing")continue;let target=byId(u.targetId);if((!target||!target.alive)&&u.phase!=="leaving")target=retargetSpecial(u);if(!target&&u.phase!=="leaving"){u.phase="leaving";u.timer=0}if(u.phase==="approach"&&target){const edge=specialEdge(u,target);u.progress=Math.min(1,u.progress+dt/C.specialApproach);const ease=1-Math.pow(1-u.progress,2);u.x=u.startX+(edge.x-u.startX)*ease;u.z=u.startZ+(edge.z-u.startZ)*ease;if(u.progress>=1){u.phase=shielded(target)?"waiting":"striking";u.timer=0}}else if(u.phase==="waiting"&&target){const edge=specialEdge(u,target);u.x=edge.x;u.z=edge.z;if(!shielded(target)){u.phase="striking";u.timer=0;if(u.team===game.playerTeam)setStatus(specialName(u.team)+" attacking",target.id+" shield dropped.");}}else if(u.phase==="striking"&&target){if(shielded(target)){u.phase="waiting";u.timer=0}else{u.timer+=dt;if(u.timer>=C.specialStrike){game.cameraShake=.8;burst(target.x,target.z,"fire",55);addRing(target.x,target.z,"fire",1.2);destroy(target);u.phase="leaving";u.timer=0;if(u.team===game.playerTeam)setStatus(target.id+" destroyed",specialName(u.team)+" completed its attack and is leaving.");sound("explode")}}}else if(u.phase==="leaving"){u.timer+=dt;u.z+=u.team===game.playerTeam?18*dt:-18*dt;u.x+=game.world>=2?(u.team===game.playerTeam?-10*dt:10*dt):(u.team==="blue"?-14*dt:14*dt);if(u.timer>=.7)game.specialUnits.splice(i,1)}}}
function updateAI(){if(game.elapsed<game.aiAt)return;const l=levels[game.difficulty],team=game.aiTeam;game.aiAt=game.elapsed+l.delay*(.85+Math.random()*.35);const special=game.specials[team];if(specialUnlocked(team)&&!special.used&&!game.specialUnits.some(u=>u.team===team)){const specialTarget=structureTargets(game.playerTeam).sort((a,b)=>b.hp-a.hp)[0];if(specialTarget)deploySpecial(team,specialTarget.id)}if(game.elapsed>=game.aiDeployAt){const towers=living(team,"tower").filter(t=>!t.deployed);if(towers.length){const soldier=spawnSoldier(towers[Math.floor(Math.random()*towers.length)],false),chance=game.difficulty==="hard"?.9:game.difficulty==="medium"?.65:.15;if(game.world===3&&game.reactor&&game.reactor.team!==team&&Math.random()<chance)sendToReactor(soldier,false);game.aiDeployAt=game.elapsed+aiDeployDelay()}else game.aiDeployAt=Infinity}if(game.world===3&&game.reactor&&game.reactor.team!==team){const chance=game.difficulty==="hard"?.42:game.difficulty==="medium"?.2:.03,candidate=living(team,"soldier").find(u=>!u.holdingReactor&&!u.reactorOrder);if(candidate&&Math.random()<chance)sendToReactor(candidate,false)}const s=game.shields[team];if(s.uses<=0||game.elapsed<s.readyAt)return;const threatened=game.projectiles.map(p=>byId(p.targetId)).find(t=>t&&t.alive&&t.team===team),endangered=living(team,"tower").find(t=>t.hp<=48),target=endangered||threatened;if(target&&Math.random()<l.shield)activateShield(team,target.id)}
function reactorController(){if(!game.reactor||!game.reactor.controllerId)return null;const controller=byId(game.reactor.controllerId);if(!controller||!controller.alive){game.reactor.controllerId=null;game.reactor.team=null;return null}return controller}
function sendToReactor(soldier,announce=true){if(game.world!==3||!game.reactor||!soldier||!soldier.alive||soldier.kind!=="soldier")return false;soldier.targetId=game.reactor.id;soldier.reactorOrder=true;soldier.holdingReactor=false;soldier.orderedUntil=Number.MAX_VALUE;if(announce){game.selectedId=soldier.id;game.manualTargetId=null;game.lastOrderFriendlyId=soldier.id;game.lastOrderTargetId=game.reactor.id;game.orderFriendlyId=null;game.orderEnemyId=null;game.orderReactor=false;setStatus(soldier.id+" capturing reactor","The soldier will remain at the reactor and control it until destroyed.");addRing(soldier.x,soldier.z,"gold",.5);addRing(game.reactor.x,game.reactor.z,"gold",.8)}return true}
function captureReactor(soldier){if(!game.reactor||!soldier.alive)return false;const controller=reactorController();if(controller&&controller.team!==soldier.team)return false;game.reactor.team=soldier.team;game.reactor.controllerId=soldier.id;game.reactor.captureFlash=1;soldier.holdingReactor=true;soldier.reactorOrder=true;soldier.targetId=game.reactor.id;soldier.x=game.reactor.x+(soldier.team===game.playerTeam?-1.1:1.1);soldier.z=game.reactor.z+(soldier.team===game.playerTeam?1.1:-1.1);addShockwave(game.reactor.x,game.reactor.z,soldier.team);burst(game.reactor.x,game.reactor.z,soldier.team,28);sound("shield");if(soldier.team===game.playerTeam)setStatus("Reactor captured","Your towers fire 25% faster and shields recharge three seconds sooner.");else setStatus("Enemy controls reactor","Destroy the soldier at the reactor to remove the enemy power bonus.");return true}
function updateStorm(){const storm=game.storm;if(game.world!==3||!storm)return;if(storm.phase==="idle"&&game.elapsed>=storm.nextAt){let lane=Math.floor(Math.random()*STORM_LANES.length);if(lane===storm.lastLane)lane=(lane+1+Math.floor(Math.random()*2))%STORM_LANES.length;storm.lane=lane;storm.lastLane=lane;storm.phase="warning";storm.until=game.elapsed+C.stormWarning;storm.nextAt+=C.stormInterval;setStatus(STORM_LANES[lane].name+" lane warning","Electrical storm arriving in three seconds. Towers in that lane will stop firing.")}else if(storm.phase==="warning"&&game.elapsed>=storm.until){storm.phase="active";storm.until=game.elapsed+C.stormActive;game.cameraShake=.25;sound("shield")}else if(storm.phase==="active"&&game.elapsed>=storm.until){storm.phase="idle";storm.lane=-1}}
function checkEnd(){if(!living(game.aiTeam,"tower").length)return endMatch("victory");if(!living(game.playerTeam,"tower").length)return endMatch("defeat")}
function addRing(x,z,color,life){game.rings.push({x,z,color,life,maxLife:life})}
function addShockwave(x,z,color){game.rings.push({x,z,color,life:.72,maxLife:.72,shockwave:true})}
function burst(x,z,color,count){for(let i=0;i<count;i++)game.particles.push({x,z,height:3+Math.random()*10,vx:(Math.random()-.5)*8,vz:(Math.random()-.5)*8,vh:5+Math.random()*13,life:.35+Math.random()*.65,maxLife:1,color,size:1.5+Math.random()*3.5})}
function updateRearming(){for(const t of game.entities){if(t.kind!=="tower"||!t.alive||!Number.isFinite(t.weaponReadyAt)||t.weaponReadyAt<=0||game.elapsed<t.weaponReadyAt)continue;t.weaponReadyAt=0;t.nextFire=game.elapsed;addRing(t.x,t.z,t.team,.75);if(t.team===game.playerTeam)setStatus(t.id+" rearmed","Tower weapon is firing again.")}}
function updateEffects(dt){for(const b of game.barriers)if(b.hitFlash>0)b.hitFlash-=dt;if(game.reactor&&game.reactor.captureFlash>0)game.reactor.captureFlash=Math.max(0,game.reactor.captureFlash-dt);for(let i=game.particles.length-1;i>=0;i--){const p=game.particles[i];p.x+=p.vx*dt;p.z+=p.vz*dt;p.height+=p.vh*dt;p.vh-=20*dt;p.life-=dt;if(p.life<=0)game.particles.splice(i,1)}for(let i=game.rings.length-1;i>=0;i--){game.rings[i].life-=dt;if(game.rings[i].life<=0)game.rings.splice(i,1)}game.cameraShake=Math.max(0,game.cameraShake-dt*1.8)}
function update(dt){game.elapsed+=dt;if(game.elapsed>game.deployArmedUntil&&ui.deploy.classList.contains("armed")){game.deployArmedUntil=0;ui.deploy.classList.remove("armed");ui.deploy.textContent="Deploy Soldier"}updateStorm();updateRearming();updateCombat(dt);updateSpecials(dt);updateAI();updateEffects(dt);updateHud();checkEnd()}

function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.5);viewport={w:r.width,h:r.height,dpr:d};canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0)}
function size(){return viewport}
function project(x,z,height=0){const s=size();if(game.world>=2){const nx=x/C.worldWidth+.5,ny=z/C.worldDepth+.5,scale=.55+ny;return{x:nx*s.w,y:ny*s.h-height*scale*Math.min(s.w,s.h)/620,scale}}const horizon=s.h*.265,t=(z+C.worldDepth/2)/C.worldDepth,scale=.44+t*1.02,field=Math.min(s.w*.88,s.h*1.55);return{x:s.w/2+x*scale*field/C.worldWidth,y:horizon+t*s.h*.62-height*scale*Math.min(s.w,s.h)/620,scale}}
function drawBackground(now){const s=size(),w=s.w,h=s.h,img=game.world===3?art.stormBackground:game.world===2?art.riftBackground:art.background;if(img.complete&&img.naturalWidth){if(game.world>=2)ctx.drawImage(img,0,0,w,h);else{const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}const shade=ctx.createLinearGradient(0,0,0,h);shade.addColorStop(0,"rgba(13,24,37,.03)");shade.addColorStop(.6,"rgba(20,12,20,0)");shade.addColorStop(1,"rgba(8,8,14,.28)");ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);return}const horizon=h*.265,sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,"#489ed4");sky.addColorStop(.7,"#86c8ec");sky.addColorStop(1,"#d0e9ef");ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon+1);ctx.fillStyle="#7b392f";ctx.fillRect(0,horizon,w,h-horizon);drawGrid();drawCrystals(now)}
function drawMountains(w,h){const layers=[["rgba(66,58,80,.42)",[0,.13,.21,.34,.46,.59,.73,.86,1]],["rgba(72,46,62,.68)",[0,.16,.29,.43,.55,.68,.82,1]]];for(const layer of layers){ctx.fillStyle=layer[0];ctx.beginPath();ctx.moveTo(0,h);layer[1].forEach((p,i)=>ctx.lineTo(p*w,i%2?h-(35+i%3*20):h-h*.06));ctx.lineTo(w,h);ctx.closePath();ctx.fill()}}
function drawGrid(){ctx.save();ctx.strokeStyle="rgba(255,205,137,.12)";ctx.lineWidth=1;for(let z=-32;z<=34;z+=7){const a=project(-23,z),b=project(23,z);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let x=-20;x<=20;x+=5){const a=project(x,-33),b=project(x,35);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}
function drawCrystals(now){const list=[[-19,-4,5,"#9b6fff"],[20,3,7,"#59d5ff"],[-22,24,9,"#8d70ff"],[22,-23,5,"#50c7eb"],[18,29,6,"#b784ff"],[-20,-27,4,"#72d7f4"]];for(const c of list){const b=project(c[0],c[1]),t=project(c[0],c[1],c[2]);ctx.save();ctx.globalAlpha=.72+Math.sin(now*.002+c[0])*.18;ctx.fillStyle=c[3];ctx.beginPath();ctx.moveTo(b.x-3*b.scale,b.y);ctx.lineTo(t.x,t.y);ctx.lineTo(b.x+4*b.scale,b.y);ctx.closePath();ctx.fill();ctx.restore()}}
function color(team){return team==="blue"?"#35c8ff":team==="red"?"#ff554e":team==="gold"?"#ffd56a":"#ffb24d"}
function barrierGeometry(b){const p=project(b.x,b.z),w=b.mapWidth*size().w,h=Math.max(70,w*.36);return{p,w,h}}
function barrierFrame(b,g){const c=Math.cos(b.angle),s=Math.sin(b.angle),half=g.w*.47;return{c,s,panelHeight:g.h*.58,postHeight:g.h*.82,left:{x:g.p.x-c*half,y:g.p.y-s*half},right:{x:g.p.x+c*half,y:g.p.y+s*half}}}
function barrierPalette(team){return team==="blue"?{energy:"#35c8ff",edge:"#9aecff",metal:"#173641",dark:"#081820",fillTop:"rgba(129,232,255,.15)",fillBottom:"rgba(32,177,236,.42)"}:{energy:"#ff5b55",edge:"#ffc0b7",metal:"#482326",dark:"#1d0b0d",fillTop:"rgba(255,173,159,.14)",fillBottom:"rgba(238,66,65,.4)"}}
function drawBarrierPost(pt,f,side,palette,heightScale=1){const height=f.postHeight*heightScale,outX=f.c*side*18,outY=f.s*side*18;ctx.save();ctx.fillStyle="rgba(0,0,0,.45)";ctx.beginPath();ctx.ellipse(pt.x,pt.y+7,24,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=palette.dark;ctx.beginPath();ctx.moveTo(pt.x-18,pt.y+5);ctx.lineTo(pt.x+18,pt.y+5);ctx.lineTo(pt.x+10,pt.y-8);ctx.lineTo(pt.x-10,pt.y-8);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(pt.x+outX,pt.y+outY+4);ctx.lineTo(pt.x+side*7,pt.y-7);ctx.lineTo(pt.x+side*13,pt.y+5);ctx.closePath();ctx.fill();ctx.fillStyle=palette.metal;ctx.beginPath();ctx.moveTo(pt.x-9,pt.y-5);ctx.lineTo(pt.x-6,pt.y-height);ctx.lineTo(pt.x+6,pt.y-height);ctx.lineTo(pt.x+9,pt.y-5);ctx.closePath();ctx.fill();ctx.strokeStyle=palette.edge;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(pt.x,pt.y-10);ctx.lineTo(pt.x,pt.y-height+7);ctx.stroke();ctx.fillStyle=palette.dark;ctx.fillRect(pt.x-10,pt.y-height-5,20,8);ctx.fillStyle=palette.energy;ctx.shadowColor=palette.energy;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(pt.x,pt.y-height-1,4,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawEnergyBarrier(b,g){const f=barrierFrame(b,g),palette=barrierPalette(b.team),inset=10,left={x:f.left.x+f.c*inset,y:f.left.y+f.s*inset},right={x:f.right.x-f.c*inset,y:f.right.y-f.s*inset};ctx.save();if(b.hitFlash>0){ctx.shadowColor="#fff";ctx.shadowBlur=28}if(b.alive){const gradient=ctx.createLinearGradient(0,Math.min(left.y,right.y)-f.panelHeight,0,Math.max(left.y,right.y));gradient.addColorStop(0,palette.fillTop);gradient.addColorStop(1,palette.fillBottom);ctx.shadowColor=palette.energy;ctx.shadowBlur=18;ctx.fillStyle=gradient;ctx.beginPath();ctx.moveTo(left.x,left.y);ctx.lineTo(right.x,right.y);ctx.lineTo(right.x,right.y-f.panelHeight);ctx.lineTo(left.x,left.y-f.panelHeight);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=palette.edge;ctx.lineWidth=2.5;ctx.stroke();ctx.save();ctx.beginPath();ctx.moveTo(left.x,left.y);ctx.lineTo(right.x,right.y);ctx.lineTo(right.x,right.y-f.panelHeight);ctx.lineTo(left.x,left.y-f.panelHeight);ctx.closePath();ctx.clip();ctx.strokeStyle=b.team==="blue"?"rgba(159,239,255,.35)":"rgba(255,205,196,.32)";ctx.lineWidth=1;for(let i=1;i<7;i++){const t=i/7,x=left.x+(right.x-left.x)*t,y=left.y+(right.y-left.y)*t;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-f.panelHeight);ctx.stroke()}for(let i=1;i<4;i++){const yOffset=f.panelHeight*i/4;ctx.beginPath();ctx.moveTo(left.x,left.y-yOffset);ctx.lineTo(right.x,right.y-yOffset);ctx.stroke()}const scan=f.panelHeight*((game.elapsed*.55)%1);ctx.strokeStyle=palette.edge;ctx.globalAlpha=.55;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(left.x,left.y-scan);ctx.lineTo(right.x,right.y-scan);ctx.stroke();ctx.restore();drawBarrierPost(f.left,f,-1,palette);drawBarrierPost(f.right,f,1,palette)}else{ctx.strokeStyle=palette.energy;ctx.globalAlpha=.38;ctx.lineWidth=3;ctx.setLineDash([12,13]);ctx.beginPath();ctx.moveTo(left.x,left.y-8);ctx.lineTo(left.x+(right.x-left.x)*.28,left.y+(right.y-left.y)*.28-f.panelHeight*.18);ctx.moveTo(right.x-(right.x-left.x)*.24,right.y-(right.y-left.y)*.24-f.panelHeight*.12);ctx.lineTo(right.x,right.y-5);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;drawBarrierPost(f.left,f,-1,palette,.48);drawBarrierPost(f.right,f,1,palette,.34)}if(b.id===game.manualTargetId){ctx.strokeStyle="#ffd56a";ctx.lineWidth=3;ctx.shadowColor="#ffd56a";ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(left.x,left.y+8);ctx.lineTo(right.x,right.y+8);ctx.lineTo(right.x,right.y-f.panelHeight-9);ctx.lineTo(left.x,left.y-f.panelHeight-9);ctx.closePath();ctx.stroke()}ctx.restore();return f}
function barrierRotationHandle(b,g=barrierGeometry(b)){const distance=g.w*.60,c=Math.cos(b.angle),s=Math.sin(b.angle);return{x:g.p.x+c*distance,y:g.p.y+s*distance,edgeX:g.p.x+c*g.w*.48,edgeY:g.p.y+s*g.w*.48,radius:Math.max(15,Math.min(20,g.w*.065)),hitRadius:Math.max(25,Math.min(32,g.w*.1))}}
function drawBarrierRotationHandle(b,g){const h=barrierRotationHandle(b,g);ctx.save();ctx.strokeStyle="#ffd56a";ctx.fillStyle="rgba(7,15,21,.94)";ctx.lineWidth=3;ctx.shadowColor="#ffd56a";ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(h.edgeX,h.edgeY);ctx.lineTo(h.x,h.y);ctx.stroke();ctx.beginPath();ctx.arc(h.x,h.y,h.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,h.radius*.45,-.65,Math.PI*1.35);ctx.stroke();const a=Math.PI*1.35,ax=h.x+Math.cos(a)*h.radius*.45,ay=h.y+Math.sin(a)*h.radius*.45;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(ax-6,ay-1);ctx.lineTo(ax-2,ay-7);ctx.closePath();ctx.fillStyle="#ffd56a";ctx.fill();ctx.restore()}
function drawBarriers(){if(game.world!==2)return;for(const b of game.barriers){const g=barrierGeometry(b),f=drawEnergyBarrier(b,g);if(game.phase==="layout"){ctx.fillStyle="rgba(5,10,14,.84)";ctx.fillRect(g.p.x-20,Math.max(f.left.y,f.right.y)+15,40,17);ctx.fillStyle="#eef8ff";ctx.font="700 11px Segoe UI";ctx.textAlign="center";ctx.fillText(b.id,g.p.x,Math.max(f.left.y,f.right.y)+28)}if(game.phase==="layout"&&b.id===game.manualTargetId)drawBarrierRotationHandle(b,g);if(b.alive)drawHealth(b,Math.min(f.left.y,f.right.y)-f.postHeight-10,Math.max(64,g.w*.55))}}
function stormEndpoints(lane){const s=size(),points=[[[0,.44],[1,.06]],[[0,.67],[1,.22]],[[0,.91],[1,.53]]][lane];return points.map(p=>({x:p[0]*s.w,y:p[1]*s.h}))}
function drawStorm(now){if(game.world!==3||!game.storm||game.storm.phase==="idle")return;const storm=game.storm,[a,b]=stormEndpoints(storm.lane),active=storm.phase==="active",pulse=.55+Math.sin(now*.012)*.18;ctx.save();ctx.lineCap="round";ctx.lineWidth=Math.max(82,Math.min(size().w,size().h)*.17);ctx.strokeStyle=active?"rgba(101,82,255,"+(pulse*.34)+")":"rgba(255,202,82,"+(pulse*.28)+")";ctx.shadowColor=active?"#79d9ff":"#ffd56a";ctx.shadowBlur=active?25:12;if(!active)ctx.setLineDash([18,14]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);if(active){const dx=b.x-a.x,dy=b.y-a.y,len=Math.max(1,Math.hypot(dx,dy)),px=-dy/len,py=dx/len;for(let bolt=0;bolt<7;bolt++){ctx.strokeStyle=bolt%2?"rgba(190,145,255,.85)":"rgba(100,224,255,.92)";ctx.lineWidth=2+bolt%3;ctx.beginPath();for(let step=0;step<=9;step++){const t=(step+bolt*.37)/9%1,offset=Math.sin(now*.018+bolt*2.1+step*1.7)*34;const x=a.x+dx*t+px*offset,y=a.y+dy*t+py*offset;if(step===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}}ctx.restore()}
function reactorScreenPoint(){const p=project(game.reactor.x,game.reactor.z);return{x:p.x,y:p.y-13*p.scale,scale:p.scale}}
function drawReactor(now){if(game.world!==3||!game.reactor)return;const r=game.reactor,p=reactorScreenPoint(),team=r.team,c=team?color(team):"#ffd56a",pulse=1+Math.sin(now*.006)*.08,selected=game.orderReactor||game.lastOrderTargetId===r.id;ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle=c;ctx.fillStyle=team?(team==="blue"?"rgba(39,187,255,.23)":"rgba(255,74,68,.21)"):"rgba(255,213,106,.13)";ctx.shadowColor=c;ctx.shadowBlur=18+(r.captureFlash||0)*22;ctx.lineWidth=selected?4:3;ctx.beginPath();ctx.ellipse(0,0,52*p.scale*pulse,22*p.scale*pulse,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.ellipse(0,0,23*p.scale*pulse,11*p.scale*pulse,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#f8fbff";ctx.beginPath();ctx.arc(0,0,5*p.scale*pulse,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font="800 "+Math.max(11,13*p.scale)+"px Segoe UI";ctx.textAlign="center";ctx.fillStyle=c;ctx.fillText(team?team.toUpperCase()+" REACTOR":"NEUTRAL REACTOR",0,-34*p.scale);ctx.restore()}
function drawShields(now){for(const u of game.entities){if(!u.alive||game.elapsed>=(u.shieldUntil||0))continue;const p=project(u.x,u.z,u.kind==="tower"?10:5),pulse=.42+Math.sin(now*.008)*.08,w=(u.kind==="tower"?42:24)*p.scale,h=(u.kind==="tower"?58:34)*p.scale;ctx.save();ctx.strokeStyle=u.team==="blue"?"rgba(67,211,255,"+(pulse+.28)+")":"rgba(255,105,95,"+(pulse+.2)+")";ctx.fillStyle=u.team==="blue"?"rgba(45,188,255,"+(pulse*.23)+")":"rgba(255,75,70,"+(pulse*.18)+")";ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,p.y,w,h,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}}
function drawHealth(u,y,width){const b=project(u.x,u.z),pct=Math.max(0,u.hp/u.maxHp);ctx.fillStyle="rgba(4,8,10,.72)";ctx.fillRect(b.x-width/2,y,width,5);ctx.fillStyle=pct<.3?"#ffd15d":color(u.team);ctx.fillRect(b.x-width/2+1,y+1,Math.max(0,(width-2)*pct),3)}
function drawTower(u,now){const b=project(u.x,u.z),s=b.scale,c=color(u.team),selected=u.id===game.selectedId,targeted=u.id===game.manualTargetId,img=u.team==="blue"?art.blueTower:art.redTower,height=116*s*(game.world===3?.72:1),width=height*.667,offline=weaponOffline(u),stormed=towerStormDisabled(u);ctx.save();ctx.fillStyle="rgba(0,0,0,.4)";ctx.beginPath();ctx.ellipse(b.x,b.y+5*s,width*.38,9*s,0,0,Math.PI*2);ctx.fill();if(!u.alive){ctx.globalAlpha=.8;ctx.filter="grayscale(1) brightness(.36)";if(img.complete&&img.naturalWidth)ctx.drawImage(img,b.x-width*.4,b.y-height*.28,width*.8,height*.28);ctx.filter="none";ctx.globalAlpha=1;ctx.fillStyle="rgba(18,15,16,.75)";ctx.beginPath();ctx.ellipse(b.x,b.y,width*.34,8*s,0,0,Math.PI*2);ctx.fill();ctx.restore();return}if(selected||targeted||u.orderedUntil>game.elapsed){ctx.strokeStyle=selected?"#ffd56a":targeted?c:"#fff0a0";ctx.lineWidth=3;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=10;ctx.beginPath();ctx.ellipse(b.x,b.y+3*s,width*.46,12*s,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}if(img.complete&&img.naturalWidth){if(offline||stormed){ctx.globalAlpha=.58;ctx.filter="saturate(.35) brightness(.7)"}if(u.hitFlash>0){ctx.shadowColor="#fff";ctx.shadowBlur=24}ctx.drawImage(img,b.x-width/2,b.y-height+7*s,width,height);ctx.filter="none";ctx.shadowBlur=0;ctx.globalAlpha=1}else{ctx.fillStyle=u.team==="blue"?"#b8d3dc":"#30353a";ctx.fillRect(b.x-width*.22,b.y-height*.82,width*.44,height*.82);ctx.fillStyle=c;ctx.fillRect(b.x-2*s,b.y-height*.78,4*s,height*.62)}if(offline){ctx.strokeStyle="#ffd56a";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x-width*.25,b.y-height*.3);ctx.lineTo(b.x+width*.25,b.y-height*.3);ctx.stroke()}if(stormed){ctx.strokeStyle="#7fe9ff";ctx.lineWidth=3;ctx.shadowColor="#7fe9ff";ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(b.x-width*.28,b.y-height*.58);ctx.lineTo(b.x,b.y-height*.46);ctx.lineTo(b.x-width*.08,b.y-height*.34);ctx.lineTo(b.x+width*.28,b.y-height*.22);ctx.stroke();ctx.shadowBlur=0}if(offline&&Number.isFinite(u.weaponReadyAt)){const remaining=Math.max(1,Math.ceil(u.weaponReadyAt-game.elapsed));ctx.font="700 "+Math.max(12,14*s)+"px Segoe UI";ctx.textAlign="center";ctx.fillStyle="#ffd56a";ctx.shadowColor="rgba(0,0,0,.9)";ctx.shadowBlur=5;ctx.fillText(remaining+"s",b.x,b.y-height-18);ctx.shadowBlur=0}drawHealth(u,b.y-height-10,width*.82);if(game.phase==="layout"){ctx.fillStyle="rgba(5,10,14,.82)";ctx.fillRect(b.x-15,b.y+10*s,30,17);ctx.fillStyle="#eef8ff";ctx.font="700 11px Segoe UI";ctx.textAlign="center";ctx.fillText(u.id,b.x,b.y+23*s)}ctx.restore()}
function shotPosition(s){const t=byId(s.targetId),p=Math.min(1,(game.elapsed-s.startAt)/s.duration),e=1-Math.pow(1-p,2),x=t?t.x:s.startX,z=t?t.z:s.startZ;return{x:s.startX+(x-s.startX)*e,z:s.startZ+(z-s.startZ)*e,height:Math.sin(p*Math.PI)*7+6,p,endX:x,endZ:z}}
function drawSoldier(u,now){if(!u.alive)return;const b=project(u.x,u.z),s=b.scale,target=byId(u.targetId),distance=target?dist(u,target):Infinity,dx=target?target.x-u.x:(u.team===game.playerTeam?-1:1),dz=target?target.z-u.z:-1,moving=target&&distance>C.smashRange+.1,structureAttack=target&&(target.kind==="tower"||target.kind==="barrier")&&distance<=C.smashRange+.1,firing=target&&!moving&&!structureAttack;let pose;if(structureAttack)pose=Math.floor(now/190)%2?"attackFire":"attackSmash";else if(firing)pose="attackFire";else if(moving&&Math.abs(dx)>Math.abs(dz)*.55)pose="walkSide";else pose=u.team===game.playerTeam?"walkAway":"walkSide";const artPose=soldierArt[u.team][pose],img=Array.isArray(artPose)?artPose[moving?Math.floor(now/150)%artPose.length:1]:artPose,height=74*s,width=height*.75,flip=pose==="walkAway"?dx>0:dx<0;ctx.save();ctx.fillStyle="rgba(0,0,0,.34)";ctx.beginPath();ctx.ellipse(b.x,b.y+3*s,13*s,5*s,0,0,Math.PI*2);ctx.fill();if(u.id===game.selectedId||u.orderedUntil>game.elapsed){ctx.strokeStyle="#ffd56a";ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(b.x,b.y+2*s,17*s,7*s,0,0,Math.PI*2);ctx.stroke()}ctx.translate(b.x,b.y+4*s);if(flip)ctx.scale(-1,1);if(u.hitFlash>0){ctx.shadowColor="#fff";ctx.shadowBlur=20}if(img.complete&&img.naturalWidth)ctx.drawImage(img,-width/2,-height,width,height);ctx.restore();drawHealth(u,b.y-height*.88,31*s)}
function drawShots(){for(const s of game.projectiles){const pos=shotPosition(s),p=project(pos.x,pos.z,pos.height),tailP=Math.max(0,pos.p-.06),tail=project(s.startX+(pos.endX-s.startX)*tailP,s.startZ+(pos.endZ-s.startZ)*tailP,pos.height);ctx.save();ctx.strokeStyle=color(s.team);ctx.shadowColor=color(s.team);ctx.shadowBlur=12;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(p.x,p.y,2.3,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawEffects(){for(const r of game.rings){const p=project(r.x,r.z),v=1-r.life/r.maxLife;ctx.save();ctx.globalAlpha=1-v;ctx.strokeStyle=color(r.color);if(r.shockwave){ctx.lineWidth=(6-v*3)*p.scale;ctx.shadowColor=color(r.color);ctx.shadowBlur=18;ctx.beginPath();ctx.ellipse(p.x,p.y,(12+v*88)*p.scale,(5+v*32)*p.scale,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=(1-v)*.75;ctx.strokeStyle="#fff7d6";ctx.lineWidth=2*p.scale;ctx.beginPath();ctx.ellipse(p.x,p.y,(7+v*64)*p.scale,(3+v*23)*p.scale,0,0,Math.PI*2);ctx.stroke()}else{ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(p.x,p.y,(8+v*38)*p.scale,(3+v*14)*p.scale,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}for(const q of game.particles){const p=project(q.x,q.z,Math.max(0,q.height));ctx.save();ctx.globalAlpha=Math.max(0,q.life/q.maxLife);ctx.fillStyle=color(q.color);ctx.beginPath();ctx.arc(p.x,p.y,q.size*p.scale,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawSpecials(now){for(const u of game.specialUnits){const target=byId(u.targetId),isGiant=u.team==="blue",img=isGiant?art.blueGiant:art.redMegalodon,p=project(u.x,u.z,isGiant?8:16),height=(isGiant?142:92)*p.scale,width=height*1.5,desired=target?Math.sign(target.x-u.x)||1:(u.team==="blue"?-1:1),baseFacing=isGiant?1:-1,flip=desired!==baseFacing;ctx.save();ctx.fillStyle="rgba(0,0,0,.42)";ctx.beginPath();ctx.ellipse(p.x,p.y+8*p.scale,width*.28,10*p.scale,0,0,Math.PI*2);ctx.fill();if(u.phase==="waiting"){ctx.strokeStyle=color(u.team);ctx.lineWidth=4;ctx.globalAlpha=.6+Math.sin(now*.01)*.25;ctx.beginPath();ctx.arc(p.x,p.y-height*.35,width*.28,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.translate(p.x,p.y);if(flip)ctx.scale(-1,1);if(u.phase==="striking"){const pulse=1+Math.sin(now*.025)*.05;ctx.scale(pulse,pulse);ctx.shadowColor=color(u.team);ctx.shadowBlur=28}if(img.complete&&img.naturalWidth)ctx.drawImage(img,-width/2,-height,width,height);ctx.restore()}}
function drawOrder(){const a=byId(game.lastOrderFriendlyId),t=byId(game.lastOrderTargetId);if(!a||!a.alive||!t||!t.alive||a.targetId!==t.id)return;const p1=project(a.x,a.z,a.kind==="tower"?14:7),p2=project(t.x,t.z,t.kind==="tower"?14:7);ctx.save();ctx.strokeStyle="rgba(255,213,106,.62)";ctx.setLineDash([7,7]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();ctx.restore()}
function render(now){const dt=Math.min(.05,Math.max(0,(now-game.lastTime)/1000));game.lastTime=now;if(game.phase==="playing")update(dt);else updateEffects(Math.min(dt,.03));const sx=game.cameraShake?(Math.random()-.5)*game.cameraShake*14:0,sy=game.cameraShake?(Math.random()-.5)*game.cameraShake*8:0;ctx.save();ctx.translate(sx,sy);drawBackground(now);drawStorm(now);drawReactor(now);drawShields(now);for(const u of game.entities.slice().sort((a,b)=>a.z-b.z))u.kind==="tower"?drawTower(u,now):drawSoldier(u,now);drawBarriers();drawShots();drawSpecials(now);drawOrder();drawEffects();ctx.restore();requestAnimationFrame(render)}
function formatTime(seconds){const n=Math.floor(seconds);return Math.floor(n/60)+":"+String(n%60).padStart(2,"0")}
function setStatus(title,text){ui.selectionTitle.textContent=title;ui.status.textContent=text}
function updateHud(){ui.blueTowers.textContent=living("blue","tower").length;ui.redTowers.textContent=living("red","tower").length;ui.matchTime.textContent=formatTime(game.elapsed);ui.matchStatus.textContent=game.world===3?(game.storm&&game.storm.phase!=="idle"?STORM_LANES[game.storm.lane].name+" "+(game.storm.phase==="warning"?"ALERT":"STORM"):"STORM "+game.worldBattle):game.world===2?"RIFT "+game.worldBattle:"BATTLE "+game.level;const t=byId(game.selectedId),selected=t&&t.alive&&t.team===game.playerTeam,valid=selected&&t.kind==="tower"&&!t.deployed;ui.deploy.disabled=!valid||game.phase!=="playing";if(!valid){game.deployArmedUntil=0;ui.deploy.classList.remove("armed");ui.deploy.textContent="Deploy Soldier"}const s=game.shields[game.playerTeam],active=game.elapsed<s.activeUntil,cooling=!active&&game.elapsed<s.readyAt;ui.shield.disabled=game.phase!=="playing"||!selected||active||cooling||s.uses<=0;ui.shield.classList.toggle("shield-ready",selected&&!active&&!cooling&&s.uses>0);ui.shield.classList.toggle("shield-active",active);ui.shield.textContent=active?"Shield "+Math.ceil(s.activeUntil-game.elapsed)+"s":cooling?"Ready "+Math.ceil(s.readyAt-game.elapsed)+"s":selected?"Shield "+t.id+" ("+s.uses+")":"Select for Shield";const special=game.specials[game.playerTeam],name=specialName(game.playerTeam),unlocked=specialUnlocked(game.playerTeam),specialActive=game.specialUnits.some(u=>u.team===game.playerTeam),target=byId(game.manualTargetId),validTarget=target&&target.alive&&target.team===game.aiTeam&&target.kind==="tower";ui.special.classList.toggle("special-ready",unlocked&&!special.used);ui.special.classList.toggle("special-active",specialActive);ui.special.disabled=game.phase!=="playing"||special.used||!unlocked;ui.special.textContent=special.used?(specialActive?name+" Active":name+" Used"):!unlocked?name+" Locked":"Deploy "+name;ui.debugUnits.textContent="Units "+living().length;ui.debugProjectiles.textContent="Shots "+game.projectiles.length;ui.debugDamage.textContent="Damage "+Math.round(game.damageDealt)}
function positionSlot(u){return[+(u.x/C.worldWidth+.5).toFixed(4),+(u.z/C.worldDepth+.5).toFixed(4)]}
function collectRiftLayout(){const slots={},barriers={};for(const group of RIFT_GROUPS){slots[group]=game.entities.filter(u=>u.kind==="tower"&&u.riftGroup===group).map(positionSlot);const b=game.barriers.find(item=>item.group===group),p=positionSlot(b);barriers[group]={nx:p[0],ny:p[1],width:+b.mapWidth.toFixed(4),angle:+b.angle.toFixed(4)}}return{slots,barriers}}
function collectStormLayout(){const lanes=STORM_LANES.map((lane,index)=>({name:lane.name,near:game.entities.filter(u=>u.kind==="tower"&&u.lane===index&&u.team===game.playerTeam).map(positionSlot),far:game.entities.filter(u=>u.kind==="tower"&&u.lane===index&&u.team===game.aiTeam).map(positionSlot)})),reactor=positionSlot(game.reactor);return{lanes,reactor}}
function saveRiftLayout(){const data=collectRiftLayout();if(!validRiftLayout(data))return null;activeRiftLayout=data;RIFT_SLOTS=data.slots;RIFT_BARRIER_SPECS=data.barriers;try{localStorage.setItem("towerBattleRiftLayout",JSON.stringify(data))}catch{}return data}
function saveStormLayout(){const data=collectStormLayout();if(!validStormLayout(data))return null;activeStormLayout=data;STORM_LANES=data.lanes;STORM_REACTOR=data.reactor;try{localStorage.setItem("towerBattleStormLayout",JSON.stringify(data))}catch{}return data}
function saveCurrentLayout(){return game.world===2?saveRiftLayout():saveStormLayout()}
function resetRiftLayout(){try{localStorage.removeItem("towerBattleRiftLayout")}catch{}activeRiftLayout=freshRiftLayout();RIFT_SLOTS=activeRiftLayout.slots;RIFT_BARRIER_SPECS=activeRiftLayout.barriers;startRiftLayoutEditor();ui.layoutMessage.textContent="Default positions restored. Drag anything to move it."}
function resetStormLayout(){try{localStorage.removeItem("towerBattleStormLayout")}catch{}activeStormLayout=freshStormLayout();STORM_LANES=activeStormLayout.lanes;STORM_REACTOR=activeStormLayout.reactor;startStormLayoutEditor();ui.layoutMessage.textContent="Default positions restored. Drag anything to move it."}
function resetCurrentLayout(){game.world===2?resetRiftLayout():resetStormLayout()}
async function copyCurrentLayout(){const data=saveCurrentLayout();if(!data)return;const text=JSON.stringify(data,null,2);try{await navigator.clipboard.writeText(text)}catch{const field=document.createElement("textarea");field.value=text;field.style.position="fixed";field.style.opacity="0";document.body.appendChild(field);field.select();document.execCommand("copy");field.remove()}ui.layoutMessage.textContent="Layout copied. Paste it into your Codex message."}
function testCurrentLayout(){saveCurrentLayout();game.worldBattle=1;game.lastResult=null;prepareMatch()}
function layoutAnchor(u){return u.kind==="reactor"?reactorScreenPoint():project(u.x,u.z)}
function layoutItemName(u){return u.kind==="reactor"?"Reactor":u.kind==="barrier"?"Shield "+u.id:u.id}
function rotationTargetAt(pt){if(game.world!==2)return null;const b=byId(game.manualTargetId);if(!b||b.kind!=="barrier")return null;const h=barrierRotationHandle(b);return Math.hypot(pt.x-h.x,pt.y-h.y)<=h.hitRadius?b:null}
function startLayoutDrag(e){e.preventDefault();const pt=point(e),rotating=rotationTargetAt(pt);if(rotating){game.layoutDrag={id:rotating.id,pointerId:e.pointerId,mode:"rotate"};ui.layoutMessage.textContent="Rotating "+layoutItemName(rotating);if(canvas.setPointerCapture)canvas.setPointerCapture(e.pointerId);return}const u=hitTest(pt);if(!u||(u.kind!=="tower"&&u.kind!=="barrier"&&u.kind!=="reactor"))return;const anchor=layoutAnchor(u);game.layoutDrag={id:u.id,pointerId:e.pointerId,mode:"move",offsetX:anchor.x-pt.x,offsetY:anchor.y-pt.y};game.selectedId=u.kind==="tower"?u.id:null;game.manualTargetId=u.kind==="barrier"?u.id:null;game.orderReactor=u.kind==="reactor";ui.layoutMessage.textContent="Moving "+layoutItemName(u);if(canvas.setPointerCapture)canvas.setPointerCapture(e.pointerId)}
function moveLayoutDrag(e){const drag=game.layoutDrag;if(game.phase!=="layout"||!drag||drag.pointerId!==e.pointerId)return;e.preventDefault();const u=byId(drag.id),pt=point(e);if(drag.mode==="rotate"){const center=project(u.x,u.z);u.angle=Math.atan2(pt.y-center.y,pt.x-center.x);return}const s=size(),screenX=pt.x+drag.offsetX,screenY=pt.y+drag.offsetY,nx=Math.max(.025,Math.min(.975,screenX/s.w)),ny=u.kind==="reactor"?Math.max(.04,Math.min(.96,(screenY+13*.55)/Math.max(1,s.h-13))):Math.max(.04,Math.min(.96,screenY/s.h)),p=mapPosition(nx,ny);u.x=p.x;u.z=p.z}
function finishLayoutDrag(e){const drag=game.layoutDrag;if(!drag||drag.pointerId!==e.pointerId)return;const u=byId(drag.id),action=drag.mode==="rotate"?" rotated":" placed";game.layoutDrag=null;saveCurrentLayout();ui.layoutMessage.textContent=(u?layoutItemName(u):"Position")+action+". Drag another item or test the battle.";if(canvas.releasePointerCapture&&canvas.hasPointerCapture&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function hitTest(pt){const hits=[];if(game.world===3&&game.reactor){const p=reactorScreenPoint(),rx=Math.max(48,Math.min(size().w,size().h)*.075),ry=rx*.55;if(Math.abs(pt.x-p.x)<=rx&&Math.abs(pt.y-p.y)<=ry)hits.push({u:game.reactor,score:Math.hypot((pt.x-p.x)/rx,(pt.y-p.y)/ry),z:game.reactor.z})}if(game.world===2)for(const u of game.barriers){if(!u.alive)continue;const g=barrierGeometry(u),dx=pt.x-g.p.x,dy=pt.y-g.p.y,c=Math.cos(u.angle),sn=Math.sin(u.angle),lx=dx/(Math.abs(c)<.15?(c<0?-.15:.15):c),ly=dy-sn*lx;if(Math.abs(lx)<=g.w*.52&&ly>=-g.h*.9&&ly<=g.h*.22)hits.push({u,score:Math.hypot(lx/g.w,ly/g.h),z:u.z})}for(const u of game.entities){if(!u.alive)continue;const base=project(u.x,u.z),s=base.scale;if(u.kind==="tower"){const worldScale=game.world===3?.72:1,width=Math.max(58,116*s*.8*worldScale),height=Math.max(76,116*s*1.08*worldScale),cx=base.x,cy=base.y-height*.46;if(Math.abs(pt.x-cx)<=width/2&&Math.abs(pt.y-cy)<=height/2)hits.push({u,score:Math.hypot((pt.x-cx)/width,(pt.y-cy)/height),z:u.z})}else{const head=project(u.x,u.z,10),width=Math.max(50,34*s),top=head.y-22,bottom=base.y+20;if(pt.x>=base.x-width/2&&pt.x<=base.x+width/2&&pt.y>=top&&pt.y<=bottom)hits.push({u,score:Math.abs(pt.x-base.x)/width,z:u.z})}}hits.sort((a,b)=>a.score-b.score||b.z-a.z);return hits.length?hits[0].u:null}
function handlePointer(e){if(game.phase==="layout")return startLayoutDrag(e);if(game.phase!=="playing")return;e.preventDefault();ensureAudio();let u=hitTest(point(e));if(!u){game.selectedId=null;game.manualTargetId=null;game.orderFriendlyId=null;game.orderEnemyId=null;game.orderReactor=false;setStatus("No unit selected",game.world===3?"Tap a soldier and the central reactor in either order, or focus fire on an enemy tower.":game.world===2?"Tap a barrier or exposed enemy tower, then one of your units.":"Tap one of your units and one enemy target, in either order.")}else if(u.kind==="reactor"){const soldier=byId(game.orderFriendlyId)||byId(game.selectedId);if(soldier&&soldier.alive&&soldier.team===game.playerTeam&&soldier.kind==="soldier")sendToReactor(soldier);else{game.orderReactor=true;game.orderEnemyId=null;game.manualTargetId=null;setStatus(u.team?u.team.toUpperCase()+" controls reactor":"Neutral reactor","Now tap one of your walking soldiers to capture it.");addRing(u.x,u.z,"gold",.8)}}else if(u.team===game.playerTeam){if(u.kind==="barrier"){game.selectedId=null;game.orderFriendlyId=null;setStatus(u.id+" barrier",Math.ceil(u.hp)+" barrier strength remaining.")}else if(game.orderReactor&&u.kind==="soldier"){sendToReactor(u)}else{game.orderReactor=false;game.selectedId=u.id;const enemy=byId(game.orderEnemyId);if(enemy&&enemy.alive)assignTarget(enemy,u);else{game.orderFriendlyId=u.id;game.orderEnemyId=null;if(u.kind==="tower")setStatus(u.id+" selected",u.deployed?"Tap an enemy target, or shield this structure.":"Tap an enemy target, deploy its soldier, or shield it.");else setStatus(u.id+" selected",game.world===3?"Tap the reactor to capture it, or tap an enemy tower.":"Tap an enemy barrier or tower for this soldier to pursue.");addRing(u.x,u.z,"gold",.45)}}}else{game.orderReactor=false;u=attackableTarget(u);const waiting=game.specialUnits.find(s=>s.team===game.playerTeam&&s.phase==="choosing");if(waiting&&(u.kind==="tower"||u.kind==="barrier")){waiting.targetId=u.id;waiting.phase="approach";waiting.progress=0;waiting.startX=waiting.x;waiting.startZ=waiting.z;game.manualTargetId=u.id;setStatus(specialName(game.playerTeam)+" targeting "+u.id,"Special attack is underway.");addRing(u.x,u.z,"red",.8)}else{const friendly=byId(game.orderFriendlyId);if(friendly&&friendly.alive&&canOrder(friendly))assignTarget(u,friendly);else{game.orderEnemyId=u.id;game.orderFriendlyId=null;game.manualTargetId=u.id;setStatus(u.id+" selected",u.kind==="barrier"?"Now tap one of your armed towers or walking soldiers to breach it.":"Now tap one of your armed towers or walking soldiers.");addRing(u.x,u.z,"red",.7)}}}updateHud()}
for(const b of document.querySelectorAll(".team-choice"))b.addEventListener("click",()=>{game.playerTeam=b.dataset.team;for(const p of document.querySelectorAll(".team-choice"))p.classList.toggle("selected",p===b);resetMatch()});
for(const b of document.querySelectorAll(".difficulty"))b.addEventListener("click",()=>{game.difficulty=b.dataset.difficulty;for(const p of document.querySelectorAll(".difficulty"))p.classList.toggle("selected",p===b)});
ui.start.addEventListener("click",startMatch);
ui.testLock.addEventListener("click",toggleTestingControls);
ui.stageStart.addEventListener("click",startMatch);
ui.level2.addEventListener("click",startLevel2);
ui.level3.addEventListener("click",startLevel3);
$("level-4-button").addEventListener("click",()=>{location.href="level4.html?team="+game.playerTeam+"&difficulty="+game.difficulty});
ui.layout2.addEventListener("click",startRiftLayoutEditor);
ui.layout3.addEventListener("click",startStormLayoutEditor);
ui.layoutReset.addEventListener("click",resetCurrentLayout);
ui.layoutCopy.addEventListener("click",copyCurrentLayout);
ui.layoutTest.addEventListener("click",testCurrentLayout);
ui.layoutMenu.addEventListener("click",showMainMenu);
ui.restart.addEventListener("click",continueBattle);
ui.pause.addEventListener("click",pauseGame);
ui.resume.addEventListener("click",resumeGame);
ui.deploy.addEventListener("click",handleDeploy);
ui.shield.addEventListener("click",()=>activateShield(game.playerTeam,game.selectedId));
ui.special.addEventListener("click",()=>deploySpecial(game.playerTeam));
for(const b of document.querySelectorAll(".menu-button"))b.addEventListener("click",showMainMenu);
canvas.addEventListener("pointerdown",handlePointer,{passive:false});
canvas.addEventListener("pointermove",moveLayoutDrag,{passive:false});
canvas.addEventListener("pointerup",finishLayoutDrag);
canvas.addEventListener("pointercancel",finishLayoutDrag);
window.addEventListener("resize",resizeCanvas);
if(window.visualViewport)window.visualViewport.addEventListener("resize",resizeCanvas);
window.addEventListener("keydown",e=>{if(e.key==="Escape"){if(game.phase==="playing")pauseGame();else if(game.phase==="paused")resumeGame();else if(game.phase==="layout")showMainMenu()}if(e.code==="Space"&&game.phase==="playing"){e.preventDefault();activateShield(game.playerTeam,game.selectedId)}if(e.key.toLowerCase()==="d")ui.debugPanel.classList.toggle("hidden")});
resetMatch();setTestingUnlocked(false);resizeCanvas();requestAnimationFrame(render);
